[[repositories]]
git = "git@github.com:mirrorboards/mirror.git"
path = "./mirror"

[[repositories]]
git = "git@github.com:open-graphene/workspace.git"
branch = "v3-graphene"
path = "."
flat = true

[[repositories]]
git = "git@github.com:bitshares/python-bitshares.git"
path = "chains/bitshares/python-bitshares"

[[repositories]]
git = "git@github.com:bitshares/bitsharesjs.git"
path = "chains/bitshares/bitsharesjs"

[[repositories]]
git = "git@github.com:bitshares/bitsharesjs-ws.git"
path = "chains/bitshares/bitsharesjs-ws"

[[repositories]]
git = "git@github.com:R-Squared-Project/R-Squared-core.git"
path = "chains/rsquared/R-Squared-core"

[[repositories]]
git = "git@github.com:R-Squared-Project/R-Squared-js.git"
path = "chains/rsquared/R-Squared-js"

[[repositories]]
git = "git@github.com:R-Squared-Project/R-Squaredjs-ws.git"
path = "chains/rsquared/R-Squaredjs-ws"

[[repositories]]
git = "git@github.com:acta-network/acta-network-core.git"
path = "chains/acta-network/acta-network-core"

[[repositories]]
git = "git@github.com:open-graphene/workspace.git"
branch = "stable-websocket-cleanup"
path = "graphene-v2"

[[repositories]]
git = "git@github.com:bitshares/bitshares-core.git"
path = "chains/bitshares/bitshares-core"

[[repositories]]
git = "git@github.com:swaplock/swaplock-core.git"
path = "chains/swaplock/swaplock-core"