// @generated by graphene-codegen; do not edit by hand.
// Source family: account (1.2.x)

graphene_protocol::define_object_id_type! {
    name: "account",
    object_space: 1,
    type_id: 2,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub membership_expiration_date: String,
    pub registrar: crate::types::account::Id,
    pub referrer: crate::types::account::Id,
    pub lifetime_referrer: crate::types::account::Id,
    pub network_fee_percentage: u16,
    pub lifetime_referrer_fee_percentage: u16,
    pub referrer_rewards_percentage: u16,
    pub name: String,
    pub owner: graphene_protocol::Authority<crate::types::account::Id>,
    pub active: graphene_protocol::Authority<crate::types::account::Id>,
    pub options: graphene_protocol::AccountOptions<crate::types::account::Id>,
    pub num_committee_voted: u16,
    pub statistics: crate::types::account_statistics::Id,
    pub whitelisting_accounts: Vec<crate::types::account::Id>,
    pub blacklisting_accounts: Vec<crate::types::account::Id>,
    pub whitelisted_accounts: Vec<crate::types::account::Id>,
    pub blacklisted_accounts: Vec<crate::types::account::Id>,
    pub cashback_vb: Option<crate::types::vesting_balance::Id>,
    pub owner_special_authority: graphene_protocol::SpecialAuthority<crate::types::asset::Id>,
    pub active_special_authority: graphene_protocol::SpecialAuthority<crate::types::asset::Id>,
    pub top_n_control_flags: u8,
    pub allowed_assets: Option<Vec<crate::types::asset::Id>>,
    pub creation_block_num: u32,
    pub creation_time: String,
}
