// @generated by graphene-codegen; do not edit by hand.
// Source family: asset_bitasset_data (2.4.x)

graphene_protocol::define_object_id_type! {
    name: "asset_bitasset_data",
    object_space: 2,
    type_id: 4,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub asset_id: crate::types::asset::Id,
    pub feeds: Vec<(
        crate::types::account::Id,
        (
            String,
            graphene_protocol::PriceFeedWithIcr<crate::types::asset::Id>,
        ),
    )>,
    pub median_feed: graphene_protocol::PriceFeedWithIcr<crate::types::asset::Id>,
    pub current_feed: graphene_protocol::PriceFeedWithIcr<crate::types::asset::Id>,
    pub current_feed_publication_time: String,
    pub current_maintenance_collateralization: graphene_protocol::Price<crate::types::asset::Id>,
    pub current_initial_collateralization: graphene_protocol::Price<crate::types::asset::Id>,
    pub options: graphene_protocol::BitAssetOptions<crate::types::asset::Id>,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub force_settled_volume: i64,
    pub is_prediction_market: bool,
    pub settlement_price: graphene_protocol::Price<crate::types::asset::Id>,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub settlement_fund: i64,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub individual_settlement_debt: i64,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub individual_settlement_fund: i64,
    pub asset_cer_updated: bool,
    pub feed_cer_updated: bool,
}
