// @generated by graphene-codegen; do not edit by hand.
// Source family: asset_bitasset_data (2.4.x)

graphene_protocol::define_object_id_type! {
    name: "asset_bitasset_data",
    object_space: 2,
    type_id: 4,
}
