// @generated by graphene-codegen; do not edit by hand.
// Source family: balance (1.15.x)

graphene_protocol::define_object_id_type! {
    name: "balance",
    object_space: 1,
    type_id: 15,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub owner: String,
    pub balance: graphene_protocol::Asset<crate::types::asset::Id>,
    pub vesting_policy: Option<graphene_protocol::LinearVestingPolicy>,
    pub last_claim_date: String,
}
