// @generated by graphene-codegen; do not edit by hand.
// Source family: budget_record (2.13.x)

graphene_protocol::define_object_id_type! {
    name: "budget_record",
    object_space: 2,
    type_id: 13,
}
