// @generated by graphene-codegen; do not edit by hand.
// Source family: chain_property (2.11.x)

graphene_protocol::define_object_id_type! {
    name: "chain_property",
    object_space: 2,
    type_id: 11,
}
