// @generated by graphene-codegen; do not edit by hand.
// Source family: credit_deal_summary (2.18.x)

graphene_protocol::define_object_id_type! {
    name: "credit_deal_summary",
    object_space: 2,
    type_id: 18,
}
