// @generated by graphene-codegen; do not edit by hand.
// Source family: credit_deal_summary (2.18.x)

graphene_protocol::define_object_id_type! {
    name: "credit_deal_summary",
    object_space: 2,
    type_id: 18,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub borrower: crate::types::account::Id,
    pub offer_id: crate::types::credit_offer::Id,
    pub offer_owner: crate::types::account::Id,
    pub debt_asset: crate::types::asset::Id,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub total_debt_amount: i64,
}
