// @generated by graphene-codegen; do not edit by hand.
// Source family: credit_offer (1.21.x)

graphene_protocol::define_object_id_type! {
    name: "credit_offer",
    object_space: 1,
    type_id: 21,
}
