// @generated by graphene-codegen; do not edit by hand.
// Source family: custom_authority (1.17.x)

graphene_protocol::define_object_id_type! {
    name: "custom_authority",
    object_space: 1,
    type_id: 17,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub account: crate::types::account::Id,
    pub enabled: bool,
    pub valid_from: String,
    pub valid_to: String,
    pub operation_type: u64,
    pub auth: graphene_protocol::Authority<crate::types::account::Id>,
    pub restrictions: Vec<(u16, graphene_protocol::Restriction)>,
    pub restriction_counter: u16,
}
