// @generated by graphene-codegen; do not edit by hand.
// Source family: dynamic_global_property (2.1.x)

graphene_protocol::define_object_id_type! {
    name: "dynamic_global_property",
    object_space: 2,
    type_id: 1,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub head_block_number: u32,
    pub head_block_id: String,
    pub time: String,
    pub current_witness: crate::types::witness::Id,
    pub next_maintenance_time: String,
    pub last_vote_tally_time: String,
    pub last_budget_time: String,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub witness_budget: i64,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub total_pob: i64,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub total_inactive: i64,
    pub accounts_registered_this_interval: u32,
    pub recently_missed_count: u32,
    #[serde(deserialize_with = "graphene_protocol::u64_from_number_or_string")]
    pub current_aslot: u64,
    #[serde(deserialize_with = "graphene_protocol::u128_from_number_or_string")]
    pub recent_slots_filled: u128,
    pub dynamic_flags: u32,
    pub last_irreversible_block_num: u32,
}
