// @generated by graphene-codegen; do not edit by hand.
// Source family: fba_accumulator (2.16.x)

graphene_protocol::define_object_id_type! {
    name: "fba_accumulator",
    object_space: 2,
    type_id: 16,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub accumulated_fba_fees: i64,
    pub designated_asset: Option<crate::types::asset::Id>,
}
