// @generated by graphene-codegen; do not edit by hand.
// Source family: fba_accumulator (2.16.x)

graphene_protocol::define_object_id_type! {
    name: "fba_accumulator",
    object_space: 2,
    type_id: 16,
}
