// @generated by graphene-codegen; do not edit by hand.
// Source family: htlc (1.16.x)

graphene_protocol::define_object_id_type! {
    name: "htlc",
    object_space: 1,
    type_id: 16,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub transfer: graphene_protocol::HtlcTransfer<crate::types::account::Id, crate::types::asset::Id>,
    pub conditions: graphene_protocol::HtlcConditions,
    pub memo: Option<graphene_protocol::MemoData>,
}
