// @generated by graphene-codegen; do not edit by hand.
// Source family: limit_order (1.7.x)

graphene_protocol::define_object_id_type! {
    name: "limit_order",
    object_space: 1,
    type_id: 7,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub expiration: String,
    pub seller: crate::types::account::Id,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub for_sale: i64,
    pub sell_price: graphene_protocol::Price<crate::types::asset::Id>,
    #[serde(deserialize_with = "graphene_protocol::u128_from_number_or_string")]
    pub filled_amount: u128,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub deferred_fee: i64,
    pub deferred_paid_fee: graphene_protocol::Asset<crate::types::asset::Id>,
    pub is_settled_debt: bool,
    pub on_fill: Vec<graphene_protocol::LimitOrderAutoAction<crate::types::asset::Id>>,
    pub take_profit_order_id: Option<crate::types::limit_order::Id>,
}
