// @generated by graphene-codegen; do not edit by hand.
// Source family: liquidity_pool (1.19.x)

graphene_protocol::define_object_id_type! {
    name: "liquidity_pool",
    object_space: 1,
    type_id: 19,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub asset_a: crate::types::asset::Id,
    pub asset_b: crate::types::asset::Id,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub balance_a: i64,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub balance_b: i64,
    pub share_asset: crate::types::asset::Id,
    pub taker_fee_percent: u16,
    pub withdrawal_fee_percent: u16,
    #[serde(deserialize_with = "graphene_protocol::u128_from_number_or_string")]
    pub virtual_value: u128,
}
