// @generated by graphene-codegen; do not edit by hand.
// Source family: proposal (1.10.x)

graphene_protocol::define_object_id_type! {
    name: "proposal",
    object_space: 1,
    type_id: 10,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub expiration_time: String,
    pub review_period_time: Option<String>,
    pub proposed_transaction: crate::transaction::Transaction,
    pub required_active_approvals: Vec<crate::types::account::Id>,
    pub available_active_approvals: Vec<crate::types::account::Id>,
    pub required_owner_approvals: Vec<crate::types::account::Id>,
    pub available_owner_approvals: Vec<crate::types::account::Id>,
    pub available_key_approvals: Vec<String>,
    pub proposer: crate::types::account::Id,
    pub fail_reason: String,
}
