// @generated by graphene-codegen; do not edit by hand.
// Source family: samet_fund (1.20.x)

graphene_protocol::define_object_id_type! {
    name: "samet_fund",
    object_space: 1,
    type_id: 20,
}
