// @generated by graphene-codegen; do not edit by hand.
// Source family: samet_fund (1.20.x)

graphene_protocol::define_object_id_type! {
    name: "samet_fund",
    object_space: 1,
    type_id: 20,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub owner_account: crate::types::account::Id,
    pub asset_type: crate::types::asset::Id,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub balance: i64,
    pub fee_rate: u32,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub unpaid_amount: i64,
}
