// @generated by graphene-codegen; do not edit by hand.
// Source family: special_authority (2.14.x)

graphene_protocol::define_object_id_type! {
    name: "special_authority",
    object_space: 2,
    type_id: 14,
}
