// @generated by graphene-codegen; do not edit by hand.
// Source family: ticket (1.18.x)

graphene_protocol::define_object_id_type! {
    name: "ticket",
    object_space: 1,
    type_id: 18,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub account: crate::types::account::Id,
    pub target_type: String,
    pub amount: graphene_protocol::Asset<crate::types::asset::Id>,
    pub current_type: String,
    pub status: String,
    pub value: i64,
    pub next_auto_update_time: String,
    pub next_type_downgrade_time: String,
}
