// @generated by graphene-codegen; do not edit by hand.
// Source family: vesting_balance (1.13.x)

graphene_protocol::define_object_id_type! {
    name: "vesting_balance",
    object_space: 1,
    type_id: 13,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub owner: crate::types::account::Id,
    pub balance: graphene_protocol::Asset<crate::types::asset::Id>,
    pub policy: graphene_protocol::VestingPolicy,
    pub balance_type: String,
}
