// @generated by graphene-codegen; do not edit by hand.
// Source family: witness_schedule (2.12.x)

graphene_protocol::define_object_id_type! {
    name: "witness_schedule",
    object_space: 2,
    type_id: 12,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub current_shuffled_witnesses: Vec<crate::types::witness::Id>,
}
