//! Code-generation tooling for Graphene-family Rust crates.
//!
//! This crate is reserved for code that reads Graphene/BitShares C++ source metadata and emits
//! Rust source files for chain crates. Runtime protocol primitives and macros used by generated
//! code belong in `graphene-protocol`.

/// One object-id family discovered from a Graphene `GRAPHENE_DEFINE_IDS(...)` macro.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ObjectFamily {
    /// Graphene object space, for example `1` for protocol ids and `2` for implementation ids.
    pub object_space: u8,
    /// Family type id inside the object space, for example `5` in `2.5.x`.
    pub type_id: u8,
    /// Source family name from the C++ macro, for example `account_balance`.
    pub name: String,
}

/// Parse all `GRAPHENE_DEFINE_IDS(...)` object families from C++ source text.
///
/// This is the first generator boundary: it extracts only facts needed by
/// `graphene_protocol::define_object_id_type!`, not Rust source text yet.
///
/// The parser intentionally supports the source shape used by Graphene core:
///
/// ```text
/// GRAPHENE_DEFINE_IDS(protocol, protocol_ids, /* prefix */, /* 1.2.x */ (account))
/// GRAPHENE_DEFINE_IDS(chain, implementation_ids, impl_, /* 2.5.x */ (account_balance))
/// ```
pub fn parse_object_families(source: &str) -> Result<Vec<ObjectFamily>, String> {
    let mut families = Vec::new();
    let mut remaining = source;

    while let Some(macro_start) = remaining.find("GRAPHENE_DEFINE_IDS") {
        remaining = &remaining[macro_start + "GRAPHENE_DEFINE_IDS".len()..];

        let Some(open_paren) = remaining.find('(') else {
            break;
        };

        let after_open = &remaining[open_paren + 1..];
        let Some((macro_body, consumed)) = take_balanced_parentheses_body(after_open) else {
            break;
        };

        families.extend(parse_define_ids_body(macro_body)?);
        remaining = &after_open[consumed..];
    }

    Ok(families)
}

/// Render the Rust module source for one generated object-id family.
///
/// The module source intentionally contains only the macro invocation. The family name, object
/// space, and type id are all emitted explicitly so generated Rust preserves the source facts from
/// `GRAPHENE_DEFINE_IDS(...)` without relying on module-name inference.
pub fn render_object_id_module(family: &ObjectFamily) -> String {
    let mut output = String::new();
    output.push_str("// @generated by graphene-codegen; do not edit by hand.\n");
    output.push_str(&format!(
        "// Source family: {} ({}.{}.x)\n\n",
        family.name, family.object_space, family.type_id
    ));

    output.push_str("graphene_protocol::define_object_id_type! {\n");
    output.push_str(&format!("    name: \"{}\",\n", family.name));
    output.push_str(&format!("    object_space: {},\n", family.object_space));
    output.push_str(&format!("    type_id: {},\n", family.type_id));
    output.push_str("}\n");

    output
}

/// Render `src/types/mod.rs` for generated object-id family modules.
pub fn render_types_mod(families: &[ObjectFamily]) -> String {
    let mut output = String::new();
    output.push_str("// @generated by graphene-codegen; do not edit by hand.\n\n");

    for family in families {
        output.push_str(&format!("pub mod {};\n", family.name));
    }

    output
}

fn parse_define_ids_body(body: &str) -> Result<Vec<ObjectFamily>, String> {
    let Some((object_space_name, family_names_source)) = define_ids_space_and_names(body) else {
        return Ok(Vec::new());
    };
    let Some(object_space) = object_space_from_name(object_space_name) else {
        return Ok(Vec::new());
    };

    parse_family_names(family_names_source, object_space)
}

fn define_ids_space_and_names(body: &str) -> Option<(&str, &str)> {
    let first_comma = find_next_code_comma(body, 0)?;
    let second_comma = find_next_code_comma(body, first_comma + 1)?;
    let third_comma = find_next_code_comma(body, second_comma + 1)?;

    Some((
        body[first_comma + 1..second_comma].trim(),
        &body[third_comma + 1..],
    ))
}

fn object_space_from_name(object_space_name: &str) -> Option<u8> {
    match object_space_name {
        "relative_protocol_ids" => Some(0),
        "protocol_ids" => Some(1),
        "implementation_ids" => Some(2),
        _ => None,
    }
}

fn find_next_code_comma(source: &str, start: usize) -> Option<usize> {
    let bytes = source.as_bytes();
    let mut index = start;

    while index < bytes.len() {
        if source[index..].starts_with("/*") {
            let comment_end = source[index + 2..].find("*/")?;
            index += comment_end + 4;
            continue;
        }

        if source[index..].starts_with("//") {
            let line_end = source[index + 2..]
                .find('\n')
                .map(|offset| index + 2 + offset)
                .unwrap_or(source.len());
            index = line_end;
            continue;
        }

        if bytes[index] == b',' {
            return Some(index);
        }

        index += 1;
    }

    None
}

fn parse_family_names(source: &str, object_space: u8) -> Result<Vec<ObjectFamily>, String> {
    let mut families = Vec::new();
    let mut next_type_id = 0u8;
    let mut pending_comment_type_id = None;
    let mut index = 0;
    let bytes = source.as_bytes();

    while index < bytes.len() {
        if source[index..].starts_with("/*") {
            if let Some(comment_end) = source[index + 2..].find("*/") {
                let comment = &source[index + 2..index + 2 + comment_end];
                pending_comment_type_id = parse_type_id_from_comment(comment);
                index += comment_end + 4;
                continue;
            }
            break;
        }

        if bytes[index] == b'(' {
            if let Some(close_offset) = source[index + 1..].find(')') {
                let name = source[index + 1..index + 1 + close_offset].trim();
                if is_family_name(name) {
                    let type_id = next_type_id;
                    if let Some(comment_type_id) = pending_comment_type_id {
                        if comment_type_id != type_id {
                            return Err(format!(
                                "GRAPHENE_DEFINE_IDS comment type id for {name} ({comment_type_id}) disagrees with declaration order ({type_id})"
                            ));
                        }
                    }
                    families.push(ObjectFamily {
                        object_space,
                        type_id,
                        name: name.to_owned(),
                    });
                    next_type_id = next_type_id.saturating_add(1);
                    pending_comment_type_id = None;
                }
                index += close_offset + 2;
                continue;
            }
            break;
        }

        index += 1;
    }

    Ok(families)
}

fn parse_type_id_from_comment(comment: &str) -> Option<u8> {
    let mut parts = comment.trim().split('.');
    let _space = parts.next()?;
    parts.next()?.trim().parse().ok()
}

fn is_family_name(name: &str) -> bool {
    !name.is_empty()
        && name
            .chars()
            .all(|character| character == '_' || character.is_ascii_alphanumeric())
}

fn take_balanced_parentheses_body(source_after_open: &str) -> Option<(&str, usize)> {
    let mut depth = 1usize;

    for (index, character) in source_after_open.char_indices() {
        match character {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 {
                    return Some((&source_after_open[..index], index + 1));
                }
            }
            _ => {}
        }
    }

    None
}

#[cfg(test)]
mod tests {
    use super::{ObjectFamily, parse_object_families, render_object_id_module, render_types_mod};

    #[test]
    fn parses_protocol_object_families() {
        let source = r#"
            GRAPHENE_DEFINE_IDS(protocol, protocol_ids, /*protocol objects are not prefixed*/,
                                /* 1.0.x  */ (null)
                                /* 1.1.x  */ (base)
                                /* 1.2.x  */ (account)
                                /* 1.3.x  */ (asset)
                               )
        "#;

        assert_eq!(
            parse_object_families(source).expect("source should parse"),
            vec![
                ObjectFamily {
                    object_space: 1,
                    type_id: 0,
                    name: "null".to_owned(),
                },
                ObjectFamily {
                    object_space: 1,
                    type_id: 1,
                    name: "base".to_owned(),
                },
                ObjectFamily {
                    object_space: 1,
                    type_id: 2,
                    name: "account".to_owned(),
                },
                ObjectFamily {
                    object_space: 1,
                    type_id: 3,
                    name: "asset".to_owned(),
                },
            ]
        );
    }

    #[test]
    fn parses_implementation_object_families() {
        let source = r#"
            GRAPHENE_DEFINE_IDS(chain, implementation_ids, impl_,
                                /* 2.0.x  */ (global_property)
                                /* 2.1.x  */ (dynamic_global_property)
                                /* 2.2.x  */ (reserved0)
                                /* 2.3.x  */ (asset_dynamic_data)
                                /* 2.4.x  */ (asset_bitasset_data)
                                /* 2.5.x  */ (account_balance)
                               )
        "#;

        assert_eq!(
            parse_object_families(source).expect("source should parse"),
            vec![
                ObjectFamily {
                    object_space: 2,
                    type_id: 0,
                    name: "global_property".to_owned(),
                },
                ObjectFamily {
                    object_space: 2,
                    type_id: 1,
                    name: "dynamic_global_property".to_owned(),
                },
                ObjectFamily {
                    object_space: 2,
                    type_id: 2,
                    name: "reserved0".to_owned(),
                },
                ObjectFamily {
                    object_space: 2,
                    type_id: 3,
                    name: "asset_dynamic_data".to_owned(),
                },
                ObjectFamily {
                    object_space: 2,
                    type_id: 4,
                    name: "asset_bitasset_data".to_owned(),
                },
                ObjectFamily {
                    object_space: 2,
                    type_id: 5,
                    name: "account_balance".to_owned(),
                },
            ]
        );
    }

    #[test]
    fn parses_family_names_before_line_comments_with_commas() {
        let source = r#"
            GRAPHENE_DEFINE_IDS(chain, implementation_ids, impl_,
                                /* 2.0.x  */ (global_property)
                                /* 2.1.x  */ (dynamic_global_property)
                                /* 2.2.x  */ (reserved0) // unused, but kept for compatibility
                                /* 2.3.x  */ (asset_dynamic_data)
                               )
        "#;

        assert_eq!(
            parse_object_families(source).expect("source should parse"),
            vec![
                ObjectFamily {
                    object_space: 2,
                    type_id: 0,
                    name: "global_property".to_owned(),
                },
                ObjectFamily {
                    object_space: 2,
                    type_id: 1,
                    name: "dynamic_global_property".to_owned(),
                },
                ObjectFamily {
                    object_space: 2,
                    type_id: 2,
                    name: "reserved0".to_owned(),
                },
                ObjectFamily {
                    object_space: 2,
                    type_id: 3,
                    name: "asset_dynamic_data".to_owned(),
                },
            ]
        );
    }

    #[test]
    fn falls_back_to_sequence_order_when_comments_are_missing() {
        let source = r#"
            GRAPHENE_DEFINE_IDS(protocol, protocol_ids, prefix_,
                                (account)
                                (asset)
                               )
        "#;

        assert_eq!(
            parse_object_families(source).expect("source should parse"),
            vec![
                ObjectFamily {
                    object_space: 1,
                    type_id: 0,
                    name: "account".to_owned(),
                },
                ObjectFamily {
                    object_space: 1,
                    type_id: 1,
                    name: "asset".to_owned(),
                },
            ]
        );
    }

    #[test]
    fn validates_comments_against_declaration_order_without_trusting_them() {
        let source = r#"
            GRAPHENE_DEFINE_IDS(protocol, protocol_ids, prefix_,
                                /* 1.99.x */ (account)
                               )
        "#;

        let error = parse_object_families(source).expect_err("comment/order mismatch should fail");
        assert!(error.contains("disagrees with declaration order"));
    }

    #[test]
    fn renders_protocol_object_id_module_with_explicit_object_space() {
        let source = render_object_id_module(&ObjectFamily {
            object_space: 1,
            type_id: 2,
            name: "account".to_owned(),
        });

        assert_eq!(
            source,
            concat!(
                "// @generated by graphene-codegen; do not edit by hand.\n",
                "// Source family: account (1.2.x)\n",
                "\n",
                "graphene_protocol::define_object_id_type! {\n",
                "    name: \"account\",\n",
                "    object_space: 1,\n",
                "    type_id: 2,\n",
                "}\n",
            )
        );
    }

    #[test]
    fn renders_implementation_object_id_module_with_explicit_object_space() {
        let source = render_object_id_module(&ObjectFamily {
            object_space: 2,
            type_id: 5,
            name: "account_balance".to_owned(),
        });

        assert_eq!(
            source,
            concat!(
                "// @generated by graphene-codegen; do not edit by hand.\n",
                "// Source family: account_balance (2.5.x)\n",
                "\n",
                "graphene_protocol::define_object_id_type! {\n",
                "    name: \"account_balance\",\n",
                "    object_space: 2,\n",
                "    type_id: 5,\n",
                "}\n",
            )
        );
    }

    #[test]
    fn renders_types_mod_for_generated_family_modules() {
        let source = render_types_mod(&[
            ObjectFamily {
                object_space: 1,
                type_id: 2,
                name: "account".to_owned(),
            },
            ObjectFamily {
                object_space: 2,
                type_id: 5,
                name: "account_balance".to_owned(),
            },
        ]);

        assert_eq!(
            source,
            concat!(
                "// @generated by graphene-codegen; do not edit by hand.\n",
                "\n",
                "pub mod account;\n",
                "pub mod account_balance;\n",
            )
        );
    }
}
