// @generated by graphene-codegen; do not edit by hand.
// Source chain: swaplock operation static_variant tags

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OperationVariantSpec {
    pub tag: u16,
    pub cpp_type: &'static str,
    pub is_virtual: bool,
}

pub const SWAPLOCK_OPERATION_VARIANTS: &[OperationVariantSpec] = &[
    OperationVariantSpec {
        tag: 0,
        cpp_type: "transfer_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 1,
        cpp_type: "limit_order_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 2,
        cpp_type: "limit_order_cancel_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 3,
        cpp_type: "call_order_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 4,
        cpp_type: "fill_order_operation",
        is_virtual: true,
    },
    OperationVariantSpec {
        tag: 5,
        cpp_type: "account_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 6,
        cpp_type: "account_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 7,
        cpp_type: "account_whitelist_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 8,
        cpp_type: "account_upgrade_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 9,
        cpp_type: "account_transfer_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 10,
        cpp_type: "asset_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 11,
        cpp_type: "asset_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 12,
        cpp_type: "asset_update_bitasset_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 13,
        cpp_type: "asset_update_feed_producers_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 14,
        cpp_type: "asset_issue_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 15,
        cpp_type: "asset_reserve_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 16,
        cpp_type: "asset_fund_fee_pool_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 17,
        cpp_type: "asset_settle_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 18,
        cpp_type: "asset_global_settle_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 19,
        cpp_type: "asset_publish_feed_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 20,
        cpp_type: "witness_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 21,
        cpp_type: "witness_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 22,
        cpp_type: "proposal_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 23,
        cpp_type: "proposal_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 24,
        cpp_type: "proposal_delete_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 25,
        cpp_type: "withdraw_permission_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 26,
        cpp_type: "withdraw_permission_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 27,
        cpp_type: "withdraw_permission_claim_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 28,
        cpp_type: "withdraw_permission_delete_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 29,
        cpp_type: "committee_member_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 30,
        cpp_type: "committee_member_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 31,
        cpp_type: "committee_member_update_global_parameters_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 32,
        cpp_type: "vesting_balance_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 33,
        cpp_type: "vesting_balance_withdraw_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 34,
        cpp_type: "worker_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 35,
        cpp_type: "custom_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 36,
        cpp_type: "assert_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 37,
        cpp_type: "balance_claim_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 38,
        cpp_type: "override_transfer_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 39,
        cpp_type: "transfer_to_blind_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 40,
        cpp_type: "blind_transfer_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 41,
        cpp_type: "transfer_from_blind_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 42,
        cpp_type: "asset_settle_cancel_operation",
        is_virtual: true,
    },
    OperationVariantSpec {
        tag: 43,
        cpp_type: "asset_claim_fees_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 44,
        cpp_type: "fba_distribute_operation",
        is_virtual: true,
    },
    OperationVariantSpec {
        tag: 45,
        cpp_type: "bid_collateral_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 46,
        cpp_type: "execute_bid_operation",
        is_virtual: true,
    },
    OperationVariantSpec {
        tag: 47,
        cpp_type: "asset_claim_pool_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 48,
        cpp_type: "asset_update_issuer_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 49,
        cpp_type: "htlc_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 50,
        cpp_type: "htlc_redeem_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 51,
        cpp_type: "htlc_redeemed_operation",
        is_virtual: true,
    },
    OperationVariantSpec {
        tag: 52,
        cpp_type: "htlc_extend_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 53,
        cpp_type: "htlc_refund_operation",
        is_virtual: true,
    },
    OperationVariantSpec {
        tag: 54,
        cpp_type: "custom_authority_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 55,
        cpp_type: "custom_authority_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 56,
        cpp_type: "custom_authority_delete_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 57,
        cpp_type: "ticket_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 58,
        cpp_type: "ticket_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 59,
        cpp_type: "liquidity_pool_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 60,
        cpp_type: "liquidity_pool_delete_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 61,
        cpp_type: "liquidity_pool_deposit_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 62,
        cpp_type: "liquidity_pool_withdraw_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 63,
        cpp_type: "liquidity_pool_exchange_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 64,
        cpp_type: "samet_fund_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 65,
        cpp_type: "samet_fund_delete_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 66,
        cpp_type: "samet_fund_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 67,
        cpp_type: "samet_fund_borrow_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 68,
        cpp_type: "samet_fund_repay_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 69,
        cpp_type: "credit_offer_create_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 70,
        cpp_type: "credit_offer_delete_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 71,
        cpp_type: "credit_offer_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 72,
        cpp_type: "credit_offer_accept_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 73,
        cpp_type: "credit_deal_repay_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 74,
        cpp_type: "credit_deal_expired_operation",
        is_virtual: true,
    },
    OperationVariantSpec {
        tag: 75,
        cpp_type: "liquidity_pool_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 76,
        cpp_type: "credit_deal_update_operation",
        is_virtual: false,
    },
    OperationVariantSpec {
        tag: 77,
        cpp_type: "limit_order_update_operation",
        is_virtual: false,
    },
];
