use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .expect("crate should live under crates/graphene-gen-rust")
        .to_path_buf()
}

fn unique_output_path(test_name: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("clock should be after epoch")
        .as_nanos();
    std::env::temp_dir().join(format!(
        "graphene-gen-rust-{test_name}-{}-{nanos}.rs",
        std::process::id()
    ))
}

#[test]
fn spec_metadata_cli_writes_rust_metadata_from_opengraphene_ir() {
    let workspace = workspace_root();
    let output_path = unique_output_path("spec-metadata");

    let output = Command::new(env!("CARGO_BIN_EXE_graphene-gen-rust-spec-metadata"))
        .args([
            workspace
                .join("specs/swaplock.opengraphene.json")
                .to_str()
                .expect("path should be UTF-8"),
            "--openrpc",
            workspace
                .join("crates/graphene-spec-gen/fixtures/swaplock.openrpc.json")
                .to_str()
                .expect("path should be UTF-8"),
            "--out",
            output_path.to_str().expect("path should be UTF-8"),
        ])
        .output()
        .expect("spec metadata command should run");

    assert!(
        output.status.success(),
        "spec metadata generation failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let generated = fs::read_to_string(&output_path).expect("generated metadata should read");
    assert!(generated.contains("pub const RPC_METHODS"));
    assert!(generated.contains("DynamicGlobalProperties"));
    assert!(generated.contains("TRANSACTION_METADATA"));
    assert!(generated.contains("@generated by graphene-gen-rust"));

    fs::remove_file(output_path).ok();
}
