// @generated by graphene-codegen; do not edit by hand.
// Source family: account_transaction_history (2.9.x)

graphene_protocol::define_object_id_type! {
    name: "account_transaction_history",
    object_space: 2,
    type_id: 9,
}
