// @generated by graphene-codegen; do not edit by hand.
// Source family: account_balance (2.5.x)

graphene_protocol::define_object_id_type! {
    name: "account_balance",
    object_space: 2,
    type_id: 5,
}
