// @generated by graphene-codegen; do not edit by hand.
// Source family: asset_dynamic_data (2.3.x)

graphene_protocol::define_object_id_type! {
    name: "asset_dynamic_data",
    object_space: 2,
    type_id: 3,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub current_supply: i64,
    pub accumulated_fees: i64,
    pub accumulated_collateral_fees: i64,
    pub fee_pool: i64,
}
