// @generated by graphene-codegen; do not edit by hand.
// Source family: commit_reveal (1.22.x)

graphene_protocol::define_object_id_type! {
    name: "commit_reveal",
    object_space: 1,
    type_id: 22,
}
