// @generated by graphene-codegen; do not edit by hand.
// Source family: committee_member (1.5.x)

graphene_protocol::define_object_id_type! {
    name: "committee_member",
    object_space: 1,
    type_id: 5,
}
