// @generated by graphene-codegen; do not edit by hand.
// Source family: ico_balance (1.23.x)

graphene_protocol::define_object_id_type! {
    name: "ico_balance",
    object_space: 1,
    type_id: 23,
}
