// @generated by graphene-codegen; do not edit by hand.
// Source family: operation_history (1.11.x)

graphene_protocol::define_object_id_type! {
    name: "operation_history",
    object_space: 1,
    type_id: 11,
}
