// @generated by graphene-codegen; do not edit by hand.
// Source family: personal_data (1.19.x)

graphene_protocol::define_object_id_type! {
    name: "personal_data",
    object_space: 1,
    type_id: 19,
}
