// @generated by graphene-codegen; do not edit by hand.
// Source family: vesting_balance (1.13.x)

graphene_protocol::define_object_id_type! {
    name: "vesting_balance",
    object_space: 1,
    type_id: 13,
}
