// @generated by graphene-codegen; do not edit by hand.
// Source family: withdraw_permission (1.12.x)

graphene_protocol::define_object_id_type! {
    name: "withdraw_permission",
    object_space: 1,
    type_id: 12,
}
