// @generated by graphene-codegen; do not edit by hand.
// Source family: account_statistics (2.6.x)

graphene_protocol::define_object_id_type! {
    name: "account_statistics",
    object_space: 2,
    type_id: 6,
}
