// @generated by graphene-codegen; do not edit by hand.
// Source family: block_summary (2.8.x)

graphene_protocol::define_object_id_type! {
    name: "block_summary",
    object_space: 2,
    type_id: 8,
}
