// @generated by graphene-codegen; do not edit by hand.
// Source family: call_order (1.8.x)

graphene_protocol::define_object_id_type! {
    name: "call_order",
    object_space: 1,
    type_id: 8,
}
