// @generated by graphene-codegen; do not edit by hand.
// Source family: committee_member (1.5.x)

graphene_protocol::define_object_id_type! {
    name: "committee_member",
    object_space: 1,
    type_id: 5,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub committee_member_account: crate::types::account::Id,
    pub vote_id: String,
    pub total_votes: u64,
    pub url: String,
}
