// @generated by graphene-codegen; do not edit by hand.
// Source family: content_card (1.20.x)

graphene_protocol::define_object_id_type! {
    name: "content_card",
    object_space: 1,
    type_id: 20,
}
