// @generated by graphene-codegen; do not edit by hand.
// Source family: custom_authority (1.17.x)

graphene_protocol::define_object_id_type! {
    name: "custom_authority",
    object_space: 1,
    type_id: 17,
}
