// @generated by graphene-codegen; do not edit by hand.
// Source family: dynamic_global_property (2.1.x)

graphene_protocol::define_object_id_type! {
    name: "dynamic_global_property",
    object_space: 2,
    type_id: 1,
}
