// @generated by graphene-codegen; do not edit by hand.
// Source family: global_property (2.0.x)

graphene_protocol::define_object_id_type! {
    name: "global_property",
    object_space: 2,
    type_id: 0,
}
