// @generated by graphene-codegen; do not edit by hand.
// Source family: limit_order (1.7.x)

graphene_protocol::define_object_id_type! {
    name: "limit_order",
    object_space: 1,
    type_id: 7,
}
