// @generated by graphene-codegen; do not edit by hand.
// Source family: permission (1.21.x)

graphene_protocol::define_object_id_type! {
    name: "permission",
    object_space: 1,
    type_id: 21,
}
