// @generated by graphene-codegen; do not edit by hand.
// Source family: room_participant (1.25.x)

graphene_protocol::define_object_id_type! {
    name: "room_participant",
    object_space: 1,
    type_id: 25,
}
