// @generated by graphene-codegen; do not edit by hand.
// Source family: transaction_history (2.7.x)

graphene_protocol::define_object_id_type! {
    name: "transaction_history",
    object_space: 2,
    type_id: 7,
}
