// @generated by graphene-codegen; do not edit by hand.
// Source family: witness_schedule (2.11.x)

graphene_protocol::define_object_id_type! {
    name: "witness_schedule",
    object_space: 2,
    type_id: 11,
}
