// @generated by graphene-codegen; do not edit by hand.
// Source family: base (1.1.x)

graphene_protocol::define_object_id_type! {
    name: "base",
    object_space: 1,
    type_id: 1,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
}
