// @generated by graphene-codegen; do not edit by hand.
// Source family: blinded_balance (2.10.x)

graphene_protocol::define_object_id_type! {
    name: "blinded_balance",
    object_space: 2,
    type_id: 10,
}
