// @generated by graphene-codegen; do not edit by hand.
// Source family: buyback (2.15.x)

graphene_protocol::define_object_id_type! {
    name: "buyback",
    object_space: 2,
    type_id: 15,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub asset_to_buy: crate::types::asset::Id,
}
