// @generated by graphene-codegen; do not edit by hand.
// Source family: collateral_bid (2.17.x)

graphene_protocol::define_object_id_type! {
    name: "collateral_bid",
    object_space: 2,
    type_id: 17,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub bidder: crate::types::account::Id,
    pub inv_swan_price: graphene_protocol::Price<crate::types::asset::Id>,
}
