// @generated by graphene-codegen; do not edit by hand.
// Source family: credit_deal (1.22.x)

graphene_protocol::define_object_id_type! {
    name: "credit_deal",
    object_space: 1,
    type_id: 22,
}
