// @generated by graphene-codegen; do not edit by hand.
// Source family: force_settlement (1.4.x)

graphene_protocol::define_object_id_type! {
    name: "force_settlement",
    object_space: 1,
    type_id: 4,
}
