// @generated by graphene-codegen; do not edit by hand.
// Source family: force_settlement (1.4.x)

graphene_protocol::define_object_id_type! {
    name: "force_settlement",
    object_space: 1,
    type_id: 4,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub owner: crate::types::account::Id,
    pub balance: graphene_protocol::Asset<crate::types::asset::Id>,
    pub settlement_date: String,
}
