// @generated by graphene-codegen; do not edit by hand.
// Source family: liquidity_pool (1.19.x)

graphene_protocol::define_object_id_type! {
    name: "liquidity_pool",
    object_space: 1,
    type_id: 19,
}
