// @generated by graphene-codegen; do not edit by hand.
// Source family: transaction_history (2.7.x)

graphene_protocol::define_object_id_type! {
    name: "transaction_history",
    object_space: 2,
    type_id: 7,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub trx: graphene_protocol::SignedTransaction,
    pub trx_id: String,
}
