// @generated by graphene-codegen; do not edit by hand.
// Source family: withdraw_permission (1.12.x)

graphene_protocol::define_object_id_type! {
    name: "withdraw_permission",
    object_space: 1,
    type_id: 12,
}

#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize)]
pub struct Object {
    pub id: Id,
    pub withdraw_from_account: crate::types::account::Id,
    pub authorized_account: crate::types::account::Id,
    pub withdrawal_limit: graphene_protocol::Asset<crate::types::asset::Id>,
    pub withdrawal_period_sec: u32,
    pub period_start_time: String,
    pub expiration: String,
    pub claimed_this_period: i64,
}
