[package]
name = "graphene-chain-rsquared"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
graphene-protocol = { path = "../graphene-protocol" }
serde = { version = "1", features = ["derive"] }

[lints]
workspace = true
