// @generated by graphene-codegen; do not edit by hand.

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct TransferOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub from: graphene_protocol::ObjectId,
    pub to: graphene_protocol::ObjectId,
    pub amount: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub memo: Option<graphene_protocol::MemoData>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct LimitOrderCreateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub seller: graphene_protocol::ObjectId,
    pub amount_to_sell: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub min_to_receive: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub expiration: String,
    pub fill_or_kill: bool,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct LimitOrderCancelOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub fee_paying_account: graphene_protocol::ObjectId,
    pub order: graphene_protocol::ObjectId,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CallOrderUpdateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub funding_account: graphene_protocol::ObjectId,
    pub delta_collateral: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub delta_debt: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct FillOrderOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub order_id: graphene_protocol::ObjectId,
    pub account_id: graphene_protocol::ObjectId,
    pub pays: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub receives: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub fill_price: graphene_protocol::Price<graphene_protocol::ObjectId>,
    pub is_maker: bool,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AccountWhitelistOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub authorizing_account: graphene_protocol::ObjectId,
    pub account_to_list: graphene_protocol::ObjectId,
    pub new_listing: u8,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AccountUpgradeOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account_to_upgrade: graphene_protocol::ObjectId,
    pub upgrade_to_lifetime_member: bool,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AccountTransferOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account_id: graphene_protocol::ObjectId,
    pub new_owner: graphene_protocol::ObjectId,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AssetUpdateFeedProducersOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub issuer: graphene_protocol::ObjectId,
    pub asset_to_update: graphene_protocol::ObjectId,
    pub new_feed_producers: Vec<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AssetIssueOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub issuer: graphene_protocol::ObjectId,
    pub asset_to_issue: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub issue_to_account: graphene_protocol::ObjectId,
    pub memo: Option<graphene_protocol::MemoData>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AssetReserveOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub payer: graphene_protocol::ObjectId,
    pub amount_to_reserve: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AssetFundFeePoolOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub from_account: graphene_protocol::ObjectId,
    pub asset_id: graphene_protocol::ObjectId,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub amount: i64,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AssetSettleOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub amount: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AssetGlobalSettleOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub issuer: graphene_protocol::ObjectId,
    pub asset_to_settle: graphene_protocol::ObjectId,
    pub settle_price: graphene_protocol::Price<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct WitnessCreateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub witness_account: graphene_protocol::ObjectId,
    pub url: String,
    pub block_signing_key: String,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct WitnessUpdateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub witness: graphene_protocol::ObjectId,
    pub witness_account: graphene_protocol::ObjectId,
    pub new_url: Option<String>,
    pub new_signing_key: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct ProposalUpdateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub fee_paying_account: graphene_protocol::ObjectId,
    pub proposal: graphene_protocol::ObjectId,
    pub active_approvals_to_add: Vec<graphene_protocol::ObjectId>,
    pub active_approvals_to_remove: Vec<graphene_protocol::ObjectId>,
    pub owner_approvals_to_add: Vec<graphene_protocol::ObjectId>,
    pub owner_approvals_to_remove: Vec<graphene_protocol::ObjectId>,
    pub key_approvals_to_add: Vec<String>,
    pub key_approvals_to_remove: Vec<String>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct ProposalDeleteOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub fee_paying_account: graphene_protocol::ObjectId,
    pub using_owner_authority: bool,
    pub proposal: graphene_protocol::ObjectId,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct WithdrawPermissionCreateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub withdraw_from_account: graphene_protocol::ObjectId,
    pub authorized_account: graphene_protocol::ObjectId,
    pub withdrawal_limit: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub withdrawal_period_sec: u32,
    pub periods_until_expiration: u32,
    pub period_start_time: String,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct WithdrawPermissionUpdateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub withdraw_from_account: graphene_protocol::ObjectId,
    pub authorized_account: graphene_protocol::ObjectId,
    pub permission_to_update: graphene_protocol::ObjectId,
    pub withdrawal_limit: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub withdrawal_period_sec: u32,
    pub period_start_time: String,
    pub periods_until_expiration: u32,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct WithdrawPermissionClaimOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub withdraw_permission: graphene_protocol::ObjectId,
    pub withdraw_from_account: graphene_protocol::ObjectId,
    pub withdraw_to_account: graphene_protocol::ObjectId,
    pub amount_to_withdraw: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub memo: Option<graphene_protocol::MemoData>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct WithdrawPermissionDeleteOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub withdraw_from_account: graphene_protocol::ObjectId,
    pub authorized_account: graphene_protocol::ObjectId,
    pub withdrawal_permission: graphene_protocol::ObjectId,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CommitteeMemberCreateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub committee_member_account: graphene_protocol::ObjectId,
    pub url: String,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CommitteeMemberUpdateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub committee_member: graphene_protocol::ObjectId,
    pub committee_member_account: graphene_protocol::ObjectId,
    pub new_url: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct VestingBalanceWithdrawOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub vesting_balance: graphene_protocol::ObjectId,
    pub owner: graphene_protocol::ObjectId,
    pub amount: graphene_protocol::Asset<graphene_protocol::ObjectId>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CustomOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub payer: graphene_protocol::ObjectId,
    pub required_auths: Vec<graphene_protocol::ObjectId>,
    pub id: u16,
    pub data: Vec<u8>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct BalanceClaimOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub deposit_to_account: graphene_protocol::ObjectId,
    pub balance_to_claim: graphene_protocol::ObjectId,
    pub balance_owner_key: String,
    pub total_claimed: graphene_protocol::Asset<graphene_protocol::ObjectId>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct OverrideTransferOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub issuer: graphene_protocol::ObjectId,
    pub from: graphene_protocol::ObjectId,
    pub to: graphene_protocol::ObjectId,
    pub amount: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub memo: Option<graphene_protocol::MemoData>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AssetSettleCancelOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub settlement: graphene_protocol::ObjectId,
    pub account: graphene_protocol::ObjectId,
    pub amount: graphene_protocol::Asset<graphene_protocol::ObjectId>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct FbaDistributeOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account_id: graphene_protocol::ObjectId,
    pub fba_id: graphene_protocol::ObjectId,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub amount: i64,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct BidCollateralOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub bidder: graphene_protocol::ObjectId,
    pub additional_collateral: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub debt_covered: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct ExecuteBidOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub bidder: graphene_protocol::ObjectId,
    pub debt: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub collateral: graphene_protocol::Asset<graphene_protocol::ObjectId>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AssetClaimPoolOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub issuer: graphene_protocol::ObjectId,
    pub asset_id: graphene_protocol::ObjectId,
    pub amount_to_claim: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct AssetUpdateIssuerOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub issuer: graphene_protocol::ObjectId,
    pub asset_to_update: graphene_protocol::ObjectId,
    pub new_issuer: graphene_protocol::ObjectId,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct HtlcRedeemOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub htlc_id: graphene_protocol::ObjectId,
    pub redeemer: graphene_protocol::ObjectId,
    pub preimage: Vec<u8>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct HtlcExtendOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub htlc_id: graphene_protocol::ObjectId,
    pub update_issuer: graphene_protocol::ObjectId,
    pub seconds_to_add: u32,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CustomAuthorityCreateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub enabled: bool,
    pub valid_from: String,
    pub valid_to: String,
    pub operation_type: u32,
    pub auth: graphene_protocol::Authority<graphene_protocol::ObjectId>,
    pub restrictions: Vec<graphene_protocol::Restriction>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CustomAuthorityUpdateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub authority_to_update: graphene_protocol::ObjectId,
    pub new_enabled: Option<bool>,
    pub new_valid_from: Option<String>,
    pub new_valid_to: Option<String>,
    pub new_auth: Option<graphene_protocol::Authority<graphene_protocol::ObjectId>>,
    pub restrictions_to_remove: Vec<u16>,
    pub restrictions_to_add: Vec<graphene_protocol::Restriction>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CustomAuthorityDeleteOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub authority_to_delete: graphene_protocol::ObjectId,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct TicketCreateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub target_type: u32,
    pub amount: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct TicketUpdateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub ticket: graphene_protocol::ObjectId,
    pub account: graphene_protocol::ObjectId,
    pub target_type: u32,
    pub amount_for_new_target: Option<graphene_protocol::Asset<graphene_protocol::ObjectId>>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct LiquidityPoolCreateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub asset_a: graphene_protocol::ObjectId,
    pub asset_b: graphene_protocol::ObjectId,
    pub share_asset: graphene_protocol::ObjectId,
    pub taker_fee_percent: u16,
    pub withdrawal_fee_percent: u16,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct LiquidityPoolDeleteOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub pool: graphene_protocol::ObjectId,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct LiquidityPoolDepositOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub pool: graphene_protocol::ObjectId,
    pub amount_a: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub amount_b: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct LiquidityPoolWithdrawOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub pool: graphene_protocol::ObjectId,
    pub share_amount: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct LiquidityPoolExchangeOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub pool: graphene_protocol::ObjectId,
    pub amount_to_sell: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub min_to_receive: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct SametFundCreateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub owner_account: graphene_protocol::ObjectId,
    pub asset_type: graphene_protocol::ObjectId,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub balance: i64,
    pub fee_rate: u32,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct SametFundDeleteOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub owner_account: graphene_protocol::ObjectId,
    pub fund_id: graphene_protocol::ObjectId,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct SametFundUpdateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub owner_account: graphene_protocol::ObjectId,
    pub fund_id: graphene_protocol::ObjectId,
    pub delta_amount: Option<graphene_protocol::Asset<graphene_protocol::ObjectId>>,
    pub new_fee_rate: Option<u32>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct SametFundBorrowOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub borrower: graphene_protocol::ObjectId,
    pub fund_id: graphene_protocol::ObjectId,
    pub borrow_amount: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct SametFundRepayOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub fund_id: graphene_protocol::ObjectId,
    pub repay_amount: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub fund_fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CreditOfferCreateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub owner_account: graphene_protocol::ObjectId,
    pub asset_type: graphene_protocol::ObjectId,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub balance: i64,
    pub fee_rate: u32,
    pub max_duration_seconds: u32,
    #[serde(deserialize_with = "graphene_protocol::i64_from_number_or_string")]
    pub min_deal_amount: i64,
    pub enabled: bool,
    pub auto_disable_time: String,
    pub acceptable_collateral: Vec<(
        graphene_protocol::ObjectId,
        graphene_protocol::Price<graphene_protocol::ObjectId>,
    )>,
    pub acceptable_borrowers: Vec<(graphene_protocol::ObjectId, i64)>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CreditOfferDeleteOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub owner_account: graphene_protocol::ObjectId,
    pub offer_id: graphene_protocol::ObjectId,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CreditOfferUpdateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub owner_account: graphene_protocol::ObjectId,
    pub offer_id: graphene_protocol::ObjectId,
    pub delta_amount: Option<graphene_protocol::Asset<graphene_protocol::ObjectId>>,
    pub fee_rate: Option<u32>,
    pub max_duration_seconds: Option<u32>,
    pub min_deal_amount: Option<i64>,
    pub enabled: Option<bool>,
    pub auto_disable_time: Option<String>,
    pub acceptable_collateral: Option<
        Vec<(
            graphene_protocol::ObjectId,
            graphene_protocol::Price<graphene_protocol::ObjectId>,
        )>,
    >,
    pub acceptable_borrowers: Option<Vec<(graphene_protocol::ObjectId, i64)>>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CreditDealRepayOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub deal_id: graphene_protocol::ObjectId,
    pub repay_amount: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub credit_fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CreditDealExpiredOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub deal_id: graphene_protocol::ObjectId,
    pub offer_id: graphene_protocol::ObjectId,
    pub offer_owner: graphene_protocol::ObjectId,
    pub borrower: graphene_protocol::ObjectId,
    pub unpaid_amount: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub collateral: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub fee_rate: u32,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct LiquidityPoolUpdateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub pool: graphene_protocol::ObjectId,
    pub taker_fee_percent: Option<u16>,
    pub withdrawal_fee_percent: Option<u16>,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize)]
pub struct CreditDealUpdateOperation {
    pub fee: graphene_protocol::Asset<graphene_protocol::ObjectId>,
    pub account: graphene_protocol::ObjectId,
    pub deal_id: graphene_protocol::ObjectId,
    pub auto_repay: u8,
    pub extensions: Vec<graphene_protocol::RestrictionArgument>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum Operation {
    Transfer(TransferOperation),
    LimitOrderCreate(LimitOrderCreateOperation),
    LimitOrderCancel(LimitOrderCancelOperation),
    CallOrderUpdate(CallOrderUpdateOperation),
    FillOrder(FillOrderOperation),
    AccountWhitelist(AccountWhitelistOperation),
    AccountUpgrade(AccountUpgradeOperation),
    AccountTransfer(AccountTransferOperation),
    AssetUpdateFeedProducers(AssetUpdateFeedProducersOperation),
    AssetIssue(AssetIssueOperation),
    AssetReserve(AssetReserveOperation),
    AssetFundFeePool(AssetFundFeePoolOperation),
    AssetSettle(AssetSettleOperation),
    AssetGlobalSettle(AssetGlobalSettleOperation),
    WitnessCreate(WitnessCreateOperation),
    WitnessUpdate(WitnessUpdateOperation),
    ProposalUpdate(ProposalUpdateOperation),
    ProposalDelete(ProposalDeleteOperation),
    WithdrawPermissionCreate(WithdrawPermissionCreateOperation),
    WithdrawPermissionUpdate(WithdrawPermissionUpdateOperation),
    WithdrawPermissionClaim(WithdrawPermissionClaimOperation),
    WithdrawPermissionDelete(WithdrawPermissionDeleteOperation),
    CommitteeMemberCreate(CommitteeMemberCreateOperation),
    CommitteeMemberUpdate(CommitteeMemberUpdateOperation),
    VestingBalanceWithdraw(VestingBalanceWithdrawOperation),
    Custom(CustomOperation),
    BalanceClaim(BalanceClaimOperation),
    OverrideTransfer(OverrideTransferOperation),
    AssetSettleCancel(AssetSettleCancelOperation),
    FbaDistribute(FbaDistributeOperation),
    BidCollateral(BidCollateralOperation),
    ExecuteBid(ExecuteBidOperation),
    AssetClaimPool(AssetClaimPoolOperation),
    AssetUpdateIssuer(AssetUpdateIssuerOperation),
    HtlcRedeem(HtlcRedeemOperation),
    HtlcExtend(HtlcExtendOperation),
    CustomAuthorityCreate(CustomAuthorityCreateOperation),
    CustomAuthorityUpdate(CustomAuthorityUpdateOperation),
    CustomAuthorityDelete(CustomAuthorityDeleteOperation),
    TicketCreate(TicketCreateOperation),
    TicketUpdate(TicketUpdateOperation),
    LiquidityPoolCreate(LiquidityPoolCreateOperation),
    LiquidityPoolDelete(LiquidityPoolDeleteOperation),
    LiquidityPoolDeposit(LiquidityPoolDepositOperation),
    LiquidityPoolWithdraw(LiquidityPoolWithdrawOperation),
    LiquidityPoolExchange(LiquidityPoolExchangeOperation),
    SametFundCreate(SametFundCreateOperation),
    SametFundDelete(SametFundDeleteOperation),
    SametFundUpdate(SametFundUpdateOperation),
    SametFundBorrow(SametFundBorrowOperation),
    SametFundRepay(SametFundRepayOperation),
    CreditOfferCreate(CreditOfferCreateOperation),
    CreditOfferDelete(CreditOfferDeleteOperation),
    CreditOfferUpdate(CreditOfferUpdateOperation),
    CreditDealRepay(CreditDealRepayOperation),
    CreditDealExpired(CreditDealExpiredOperation),
    LiquidityPoolUpdate(LiquidityPoolUpdateOperation),
    CreditDealUpdate(CreditDealUpdateOperation),
    Unsupported {
        tag: u16,
        payload: serde_json::Value,
    },
}

impl Operation {
    pub fn tag(&self) -> u16 {
        match self {
            Self::Transfer(_) => 0,
            Self::LimitOrderCreate(_) => 1,
            Self::LimitOrderCancel(_) => 2,
            Self::CallOrderUpdate(_) => 3,
            Self::FillOrder(_) => 4,
            Self::AccountWhitelist(_) => 7,
            Self::AccountUpgrade(_) => 8,
            Self::AccountTransfer(_) => 9,
            Self::AssetUpdateFeedProducers(_) => 13,
            Self::AssetIssue(_) => 14,
            Self::AssetReserve(_) => 15,
            Self::AssetFundFeePool(_) => 16,
            Self::AssetSettle(_) => 17,
            Self::AssetGlobalSettle(_) => 18,
            Self::WitnessCreate(_) => 20,
            Self::WitnessUpdate(_) => 21,
            Self::ProposalUpdate(_) => 23,
            Self::ProposalDelete(_) => 24,
            Self::WithdrawPermissionCreate(_) => 25,
            Self::WithdrawPermissionUpdate(_) => 26,
            Self::WithdrawPermissionClaim(_) => 27,
            Self::WithdrawPermissionDelete(_) => 28,
            Self::CommitteeMemberCreate(_) => 29,
            Self::CommitteeMemberUpdate(_) => 30,
            Self::VestingBalanceWithdraw(_) => 33,
            Self::Custom(_) => 35,
            Self::BalanceClaim(_) => 37,
            Self::OverrideTransfer(_) => 38,
            Self::AssetSettleCancel(_) => 42,
            Self::FbaDistribute(_) => 44,
            Self::BidCollateral(_) => 45,
            Self::ExecuteBid(_) => 46,
            Self::AssetClaimPool(_) => 47,
            Self::AssetUpdateIssuer(_) => 48,
            Self::HtlcRedeem(_) => 50,
            Self::HtlcExtend(_) => 52,
            Self::CustomAuthorityCreate(_) => 54,
            Self::CustomAuthorityUpdate(_) => 55,
            Self::CustomAuthorityDelete(_) => 56,
            Self::TicketCreate(_) => 57,
            Self::TicketUpdate(_) => 58,
            Self::LiquidityPoolCreate(_) => 59,
            Self::LiquidityPoolDelete(_) => 60,
            Self::LiquidityPoolDeposit(_) => 61,
            Self::LiquidityPoolWithdraw(_) => 62,
            Self::LiquidityPoolExchange(_) => 63,
            Self::SametFundCreate(_) => 64,
            Self::SametFundDelete(_) => 65,
            Self::SametFundUpdate(_) => 66,
            Self::SametFundBorrow(_) => 67,
            Self::SametFundRepay(_) => 68,
            Self::CreditOfferCreate(_) => 69,
            Self::CreditOfferDelete(_) => 70,
            Self::CreditOfferUpdate(_) => 71,
            Self::CreditDealRepay(_) => 73,
            Self::CreditDealExpired(_) => 74,
            Self::LiquidityPoolUpdate(_) => 75,
            Self::CreditDealUpdate(_) => 76,
            Self::Unsupported { tag, .. } => *tag,
        }
    }

    pub fn is_typed(&self) -> bool {
        !matches!(self, Self::Unsupported { .. })
    }
}

impl<'de> serde::Deserialize<'de> for Operation {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        let serde_json::Value::Array(mut elements) = value else {
            return Err(serde::de::Error::custom(
                "operation static_variant must be a two-element array",
            ));
        };
        if elements.len() != 2 {
            return Err(serde::de::Error::custom(
                "operation static_variant must be a two-element array",
            ));
        }
        let payload = elements.pop().expect("length checked");
        let tag_value = elements.pop().expect("length checked");
        let tag_u64 = tag_value.as_u64().ok_or_else(|| {
            serde::de::Error::custom("operation static_variant tag must be an unsigned integer")
        })?;
        let tag = u16::try_from(tag_u64).map_err(|_| {
            serde::de::Error::custom("operation static_variant tag must fit in u16")
        })?;

        match tag {
            0 => serde_json::from_value(payload)
                .map(Self::Transfer)
                .map_err(serde::de::Error::custom),
            1 => serde_json::from_value(payload)
                .map(Self::LimitOrderCreate)
                .map_err(serde::de::Error::custom),
            2 => serde_json::from_value(payload)
                .map(Self::LimitOrderCancel)
                .map_err(serde::de::Error::custom),
            3 => serde_json::from_value(payload)
                .map(Self::CallOrderUpdate)
                .map_err(serde::de::Error::custom),
            4 => serde_json::from_value(payload)
                .map(Self::FillOrder)
                .map_err(serde::de::Error::custom),
            7 => serde_json::from_value(payload)
                .map(Self::AccountWhitelist)
                .map_err(serde::de::Error::custom),
            8 => serde_json::from_value(payload)
                .map(Self::AccountUpgrade)
                .map_err(serde::de::Error::custom),
            9 => serde_json::from_value(payload)
                .map(Self::AccountTransfer)
                .map_err(serde::de::Error::custom),
            13 => serde_json::from_value(payload)
                .map(Self::AssetUpdateFeedProducers)
                .map_err(serde::de::Error::custom),
            14 => serde_json::from_value(payload)
                .map(Self::AssetIssue)
                .map_err(serde::de::Error::custom),
            15 => serde_json::from_value(payload)
                .map(Self::AssetReserve)
                .map_err(serde::de::Error::custom),
            16 => serde_json::from_value(payload)
                .map(Self::AssetFundFeePool)
                .map_err(serde::de::Error::custom),
            17 => serde_json::from_value(payload)
                .map(Self::AssetSettle)
                .map_err(serde::de::Error::custom),
            18 => serde_json::from_value(payload)
                .map(Self::AssetGlobalSettle)
                .map_err(serde::de::Error::custom),
            20 => serde_json::from_value(payload)
                .map(Self::WitnessCreate)
                .map_err(serde::de::Error::custom),
            21 => serde_json::from_value(payload)
                .map(Self::WitnessUpdate)
                .map_err(serde::de::Error::custom),
            23 => serde_json::from_value(payload)
                .map(Self::ProposalUpdate)
                .map_err(serde::de::Error::custom),
            24 => serde_json::from_value(payload)
                .map(Self::ProposalDelete)
                .map_err(serde::de::Error::custom),
            25 => serde_json::from_value(payload)
                .map(Self::WithdrawPermissionCreate)
                .map_err(serde::de::Error::custom),
            26 => serde_json::from_value(payload)
                .map(Self::WithdrawPermissionUpdate)
                .map_err(serde::de::Error::custom),
            27 => serde_json::from_value(payload)
                .map(Self::WithdrawPermissionClaim)
                .map_err(serde::de::Error::custom),
            28 => serde_json::from_value(payload)
                .map(Self::WithdrawPermissionDelete)
                .map_err(serde::de::Error::custom),
            29 => serde_json::from_value(payload)
                .map(Self::CommitteeMemberCreate)
                .map_err(serde::de::Error::custom),
            30 => serde_json::from_value(payload)
                .map(Self::CommitteeMemberUpdate)
                .map_err(serde::de::Error::custom),
            33 => serde_json::from_value(payload)
                .map(Self::VestingBalanceWithdraw)
                .map_err(serde::de::Error::custom),
            35 => serde_json::from_value(payload)
                .map(Self::Custom)
                .map_err(serde::de::Error::custom),
            37 => serde_json::from_value(payload)
                .map(Self::BalanceClaim)
                .map_err(serde::de::Error::custom),
            38 => serde_json::from_value(payload)
                .map(Self::OverrideTransfer)
                .map_err(serde::de::Error::custom),
            42 => serde_json::from_value(payload)
                .map(Self::AssetSettleCancel)
                .map_err(serde::de::Error::custom),
            44 => serde_json::from_value(payload)
                .map(Self::FbaDistribute)
                .map_err(serde::de::Error::custom),
            45 => serde_json::from_value(payload)
                .map(Self::BidCollateral)
                .map_err(serde::de::Error::custom),
            46 => serde_json::from_value(payload)
                .map(Self::ExecuteBid)
                .map_err(serde::de::Error::custom),
            47 => serde_json::from_value(payload)
                .map(Self::AssetClaimPool)
                .map_err(serde::de::Error::custom),
            48 => serde_json::from_value(payload)
                .map(Self::AssetUpdateIssuer)
                .map_err(serde::de::Error::custom),
            50 => serde_json::from_value(payload)
                .map(Self::HtlcRedeem)
                .map_err(serde::de::Error::custom),
            52 => serde_json::from_value(payload)
                .map(Self::HtlcExtend)
                .map_err(serde::de::Error::custom),
            54 => serde_json::from_value(payload)
                .map(Self::CustomAuthorityCreate)
                .map_err(serde::de::Error::custom),
            55 => serde_json::from_value(payload)
                .map(Self::CustomAuthorityUpdate)
                .map_err(serde::de::Error::custom),
            56 => serde_json::from_value(payload)
                .map(Self::CustomAuthorityDelete)
                .map_err(serde::de::Error::custom),
            57 => serde_json::from_value(payload)
                .map(Self::TicketCreate)
                .map_err(serde::de::Error::custom),
            58 => serde_json::from_value(payload)
                .map(Self::TicketUpdate)
                .map_err(serde::de::Error::custom),
            59 => serde_json::from_value(payload)
                .map(Self::LiquidityPoolCreate)
                .map_err(serde::de::Error::custom),
            60 => serde_json::from_value(payload)
                .map(Self::LiquidityPoolDelete)
                .map_err(serde::de::Error::custom),
            61 => serde_json::from_value(payload)
                .map(Self::LiquidityPoolDeposit)
                .map_err(serde::de::Error::custom),
            62 => serde_json::from_value(payload)
                .map(Self::LiquidityPoolWithdraw)
                .map_err(serde::de::Error::custom),
            63 => serde_json::from_value(payload)
                .map(Self::LiquidityPoolExchange)
                .map_err(serde::de::Error::custom),
            64 => serde_json::from_value(payload)
                .map(Self::SametFundCreate)
                .map_err(serde::de::Error::custom),
            65 => serde_json::from_value(payload)
                .map(Self::SametFundDelete)
                .map_err(serde::de::Error::custom),
            66 => serde_json::from_value(payload)
                .map(Self::SametFundUpdate)
                .map_err(serde::de::Error::custom),
            67 => serde_json::from_value(payload)
                .map(Self::SametFundBorrow)
                .map_err(serde::de::Error::custom),
            68 => serde_json::from_value(payload)
                .map(Self::SametFundRepay)
                .map_err(serde::de::Error::custom),
            69 => serde_json::from_value(payload)
                .map(Self::CreditOfferCreate)
                .map_err(serde::de::Error::custom),
            70 => serde_json::from_value(payload)
                .map(Self::CreditOfferDelete)
                .map_err(serde::de::Error::custom),
            71 => serde_json::from_value(payload)
                .map(Self::CreditOfferUpdate)
                .map_err(serde::de::Error::custom),
            73 => serde_json::from_value(payload)
                .map(Self::CreditDealRepay)
                .map_err(serde::de::Error::custom),
            74 => serde_json::from_value(payload)
                .map(Self::CreditDealExpired)
                .map_err(serde::de::Error::custom),
            75 => serde_json::from_value(payload)
                .map(Self::LiquidityPoolUpdate)
                .map_err(serde::de::Error::custom),
            76 => serde_json::from_value(payload)
                .map(Self::CreditDealUpdate)
                .map_err(serde::de::Error::custom),
            _ => Ok(Self::Unsupported { tag, payload }),
        }
    }
}
