[chain]
name = "swaplock"
core_root = "../../chains/swaplock/swaplock-core"

[openrpc]
api_header = "libraries/app/include/graphene/app/database_api.hpp"
api_qualified_name = "graphene::app::database_api"
excluded_methods = [
  "set_subscribe_callback",
  "set_pending_transaction_callback",
  "set_block_applied_callback",
  "subscribe_to_market",
]
output = "../target/generated/swaplock/spec.json"
header_roots = [
  "libraries/protocol",
  "libraries/chain",
  "libraries/app",
  "libraries/wallet",
  "libraries/plugins",
]

[rust]
schema_output = "../target/generated/swaplock/schema.json"
variants_rs = "../crates/graphene-chain-swaplock/src/generated/variants.rs"
variants_names = "../crates/graphene-chain-swaplock/src/generated/variants.names"
types_rs = "../crates/graphene-chain-swaplock/src/generated/types.rs"
rpc_rs = "../crates/graphene-chain-swaplock/src/generated/rpc.rs"
schema_title = "swaplock_types_root"
