[package]
name = "graphene-gen-dart"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
graphene-spec-gen = { path = "../graphene-spec-gen" }
serde_json.workspace = true

[lib]
name = "graphene_gen_dart"
path = "src/lib.rs"

[[bin]]
name = "graphene-gen-dart"
path = "src/bin/graphene-gen-dart.rs"
