[package]
name = "graphene-gen-rust"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
graphene-spec-gen = { path = "../graphene-spec-gen" }
prettyplease.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
syn.workspace = true
typify.workspace = true

[lib]
name = "graphene_gen_rust"
path = "src/lib.rs"

[[bin]]
name = "graphene-gen-rust-spec-metadata"
path = "src/bin/spec-metadata.rs"

[[bin]]
name = "openrpc-typify"
path = "src/bin/openrpc-typify.rs"
