use std::path::PathBuf;

use crate::emit::{EmitError, GeneratedFile};
use crate::ir::{IrCallbackLifetime, IrCodecKind, IrDocument, IrTypeRef};

pub fn emit_dart(ir: &IrDocument) -> Result<Vec<GeneratedFile>, EmitError> {
    let mut output = String::new();
    output.push_str("// @generated by graphene-spec-gen. Do not edit.\n");
    output.push_str(&format!("// Chain: {}\n\n", ir.chain.name));

    output.push_str("class OperationMetadata {\n");
    output.push_str("  final int id;\n");
    output.push_str("  final String name;\n");
    output.push_str("  final String type;\n\n");
    output.push_str(
        "  const OperationMetadata({required this.id, required this.name, required this.type});\n",
    );
    output.push_str("}\n\n");

    output.push_str("class RpcMethodDescriptor {\n");
    output.push_str("  final String api;\n");
    output.push_str("  final List<String> params;\n");
    output.push_str("  final String? result;\n");
    output.push_str("  final String? callback;\n\n");
    output.push_str("  const RpcMethodDescriptor({required this.api, required this.params, this.result, this.callback});\n");
    output.push_str("}\n\n");

    output.push_str("class CallbackMetadata {\n");
    output.push_str("  final String api;\n");
    output.push_str("  final String payload;\n");
    output.push_str("  final String lifetime;\n");
    output.push_str("  final int callbackParamPosition;\n\n");
    output.push_str("  const CallbackMetadata({required this.api, required this.payload, required this.lifetime, required this.callbackParamPosition});\n");
    output.push_str("}\n\n");

    output.push_str("class TransactionDigestMetadata {\n");
    output.push_str("  final String algorithm;\n");
    output.push_str("  final List<String> preimage;\n\n");
    output.push_str(
        "  const TransactionDigestMetadata({required this.algorithm, required this.preimage});\n",
    );
    output.push_str("}\n\n");

    output.push_str("class TransactionSignatureMetadata {\n");
    output.push_str("  final String curve;\n");
    output.push_str("  final String format;\n");
    output.push_str("  final bool canonical;\n\n");
    output.push_str("  const TransactionSignatureMetadata({required this.curve, required this.format, required this.canonical});\n");
    output.push_str("}\n\n");

    output.push_str("class TransactionMetadata {\n");
    output.push_str("  final String type;\n");
    output.push_str("  final String operationVariant;\n");
    output.push_str("  final TransactionDigestMetadata digest;\n");
    output.push_str("  final TransactionSignatureMetadata signature;\n\n");
    output.push_str("  const TransactionMetadata({required this.type, required this.operationVariant, required this.digest, required this.signature});\n");
    output.push_str("}\n\n");

    for name in ir.operation_variants.keys() {
        output.push_str(&format!("abstract class {} {{\n", name));
        output.push_str("  int get id;\n");
        output.push_str("  String get kind;\n");
        output.push_str("  Object get value;\n\n");
        output.push_str(&format!("  const {}();\n", name));
        output.push_str("}\n\n");
    }

    for codec_type in ir.codec_types.values() {
        match codec_type.kind {
            IrCodecKind::Struct => {
                output.push_str(&format!("class {} {{\n", codec_type.name));
                for field in &codec_type.fields {
                    let ty = dart_type(
                        ir,
                        &field.type_ref,
                        &format!("codecTypes.{}.fields.{}", codec_type.name, field.name),
                    )?;
                    output.push_str(&format!("  final {} {};\n", ty, field.name));
                }
                output.push('\n');
                output.push_str(&format!("  const {}({{\n", codec_type.name));
                for field in &codec_type.fields {
                    output.push_str(&format!("    required this.{},\n", field.name));
                }
                output.push_str("  });\n");
                output.push_str("}\n\n");
            }
        }
    }

    for (name, variants) in &ir.operation_variants {
        for variant in variants {
            let dart_variant = dart_type(
                ir,
                &variant.type_ref,
                &format!("operations.{name}.{}", variant.name),
            )?;
            let class_name = format!("{}{}Operation", upper_camel(&variant.name), name);
            output.push_str(&format!("class {} extends {} {{\n", class_name, name));
            output.push_str(&format!("  final {} typedValue;\n\n", dart_variant));
            output.push_str(&format!("  const {}(this.typedValue);\n\n", class_name));
            output.push_str("  @override\n");
            output.push_str(&format!("  int get id => {};\n\n", variant.id));
            output.push_str("  @override\n");
            output.push_str(&format!("  String get kind => '{}';\n\n", variant.name));
            output.push_str("  @override\n");
            output.push_str("  Object get value => typedValue;\n");
            output.push_str("}\n\n");
        }
    }

    output.push_str("const Map<String, List<OperationMetadata>> operationMetadata = {\n");
    for (name, variants) in &ir.operation_variants {
        output.push_str(&format!("  '{}': [\n", name));
        for variant in variants {
            output.push_str(&format!(
                "    OperationMetadata(id: {}, name: '{}', type: '{}'),\n",
                variant.id,
                variant.name,
                named_type_name(&variant.type_ref).unwrap_or("<complex>")
            ));
        }
        output.push_str("  ],\n");
    }
    output.push_str("};\n\n");

    output.push_str("const Map<String, RpcMethodDescriptor> rpcMethods = {\n");
    for method in ir.methods.values() {
        output.push_str(&format!("  '{}': RpcMethodDescriptor(\n", method.name));
        output.push_str(&format!("    api: '{}',\n", method.api));
        output.push_str("    params: [");
        for (index, param) in method.params.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            output.push_str(&format!("'{}'", type_ref_label(param)));
            let _ = dart_type(
                ir,
                param,
                &format!("methods.{}.params[{index}]", method.name),
            )?;
        }
        output.push_str("],\n");
        if let Some(result) = &method.result {
            let _ = dart_type(ir, result, &format!("methods.{}.result", method.name))?;
            output.push_str(&format!("    result: '{}',\n", type_ref_label(result)));
        }
        if let Some(callback) = &method.callback {
            output.push_str(&format!("    callback: '{}',\n", callback));
        }
        output.push_str("  ),\n");
    }
    output.push_str("};\n\n");

    output.push_str("const Map<String, CallbackMetadata> callbackMetadata = {\n");
    for callback in ir.callbacks.values() {
        let _ = dart_type(
            ir,
            &callback.callback_payload,
            &format!("callbacks.{}.callbackPayload", callback.name),
        )?;
        output.push_str(&format!("  '{}': CallbackMetadata(\n", callback.name));
        output.push_str(&format!("    api: '{}',\n", callback.api));
        output.push_str(&format!(
            "    payload: '{}',\n",
            type_ref_label(&callback.callback_payload)
        ));
        output.push_str(&format!(
            "    lifetime: '{}',\n",
            callback_lifetime(callback.callback_lifetime)
        ));
        output.push_str(&format!(
            "    callbackParamPosition: {},\n",
            callback.callback_param.position
        ));
        output.push_str("  ),\n");
    }
    output.push_str("};\n\n");

    if let Some(transaction) = &ir.transaction {
        let _ = dart_type(ir, &transaction.type_ref, "transaction.type")?;
        output.push_str("const TransactionMetadata transactionMetadata = TransactionMetadata(\n");
        output.push_str(&format!(
            "  type: '{}',\n",
            type_ref_label(&transaction.type_ref)
        ));
        output.push_str(&format!(
            "  operationVariant: '{}',\n",
            transaction.operation_variant
        ));
        output.push_str("  digest: TransactionDigestMetadata(algorithm: 'sha256', preimage: ['chain_id', 'serialized_transaction']),\n");
        output.push_str("  signature: TransactionSignatureMetadata(curve: 'secp256k1', format: 'graphene_compact_recoverable', canonical: true),\n");
        output.push_str(");\n");
    }

    Ok(vec![GeneratedFile::new(
        PathBuf::from("dart/lib/open_graphene.dart"),
        output,
    )?])
}

fn dart_type(ir: &IrDocument, type_ref: &IrTypeRef, path: &str) -> Result<String, EmitError> {
    match type_ref {
        IrTypeRef::Named { name } => map_named_type(ir, name, path),
        IrTypeRef::Array { item } => Ok(format!("List<{}>", dart_type(ir, item, path)?)),
        IrTypeRef::Optional { item } => Ok(format!("{}?", dart_type(ir, item, path)?)),
    }
}

fn map_named_type(ir: &IrDocument, name: &str, path: &str) -> Result<String, EmitError> {
    let mapped = match name {
        "bool" => Some("bool".to_owned()),
        "string" | "object_id" | "time_point_sec" | "bytes" | "signature" => {
            Some("String".to_owned())
        }
        "int8" | "uint8" | "int16" | "uint16" | "int32" | "uint32" => Some("int".to_owned()),
        "int64" | "uint64" => Some("String".to_owned()),
        "void" => Some("void".to_owned()),
        custom
            if ir.codec_types.contains_key(custom)
                || ir.operation_variants.contains_key(custom) =>
        {
            Some(custom.to_owned())
        }
        _ => None,
    };

    mapped.ok_or_else(|| EmitError::new(path, format!("cannot map IR type '{name}' to Dart")))
}

fn type_ref_label(type_ref: &IrTypeRef) -> String {
    match type_ref {
        IrTypeRef::Named { name } => name.clone(),
        IrTypeRef::Array { item } => format!("{}[]", type_ref_label(item)),
        IrTypeRef::Optional { item } => format!("{}?", type_ref_label(item)),
    }
}

fn named_type_name(type_ref: &IrTypeRef) -> Option<&str> {
    match type_ref {
        IrTypeRef::Named { name } => Some(name),
        _ => None,
    }
}

fn callback_lifetime(lifetime: IrCallbackLifetime) -> &'static str {
    match lifetime {
        IrCallbackLifetime::Once => "once",
        IrCallbackLifetime::Persistent => "persistent",
    }
}

fn upper_camel(value: &str) -> String {
    let mut output = String::new();
    for part in value.split('_').filter(|part| !part.is_empty()) {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            output.extend(first.to_uppercase());
            output.push_str(chars.as_str());
        }
    }
    output
}
