use std::path::PathBuf;

use crate::emit::{EmitError, GeneratedFile};
use crate::ir::{IrCallbackLifetime, IrCodecKind, IrDocument, IrTypeRef};

pub fn emit_typescript(ir: &IrDocument) -> Result<Vec<GeneratedFile>, EmitError> {
    let mut output = String::new();
    output.push_str("// @generated by graphene-spec-gen. Do not edit.\n");
    output.push_str(&format!("// Chain: {}\n\n", ir.chain.name));

    for codec_type in ir.codec_types.values() {
        match codec_type.kind {
            IrCodecKind::Struct => {
                output.push_str(&format!("export interface {} {{\n", codec_type.name));
                for field in &codec_type.fields {
                    let ty = ts_type(
                        ir,
                        &field.type_ref,
                        &format!("codecTypes.{}.fields.{}", codec_type.name, field.name),
                    )?;
                    output.push_str(&format!("  {}: {};\n", field.name, ty));
                }
                output.push_str("}\n\n");
            }
        }
    }

    for (name, variants) in &ir.operation_variants {
        output.push_str(&format!("export type {} =\n", name));
        for (index, variant) in variants.iter().enumerate() {
            let ts_variant = ts_type(
                ir,
                &variant.type_ref,
                &format!("operations.{name}.{}", variant.name),
            )?;
            let prefix = if index == 0 { "  " } else { "  | " };
            if index + 1 == variants.len() {
                output.push_str(&format!(
                    "{}{{ kind: '{}'; id: {}; value: {} }};\n\n",
                    prefix, variant.name, variant.id, ts_variant
                ));
            } else {
                output.push_str(&format!(
                    "{}{{ kind: '{}'; id: {}; value: {} }}\n",
                    prefix, variant.name, variant.id, ts_variant
                ));
            }
        }
    }

    output.push_str("export const operationMetadata = {\n");
    for (name, variants) in &ir.operation_variants {
        output.push_str(&format!("  {}: [\n", name));
        for variant in variants {
            output.push_str(&format!(
                "    {{ id: {}, name: '{}', type: '{}' }},\n",
                variant.id,
                variant.name,
                named_type_name(&variant.type_ref).unwrap_or("<complex>")
            ));
        }
        output.push_str("  ],\n");
    }
    output.push_str("} as const;\n\n");

    output.push_str("export const rpcMethods = {\n");
    for method in ir.methods.values() {
        output.push_str(&format!("  {}: {{\n", method.name));
        output.push_str(&format!("    api: '{}',\n", method.api));
        output.push_str("    params: [");
        for (index, param) in method.params.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            output.push_str(&format!("'{}'", type_ref_label(param)));
            let _ = ts_type(
                ir,
                param,
                &format!("methods.{}.params[{index}]", method.name),
            )?;
        }
        output.push_str("],\n");
        if let Some(result) = &method.result {
            let _ = ts_type(ir, result, &format!("methods.{}.result", method.name))?;
            output.push_str(&format!("    result: '{}',\n", type_ref_label(result)));
        } else {
            output.push_str("    result: undefined,\n");
        }
        if let Some(callback) = &method.callback {
            output.push_str(&format!("    callback: '{}',\n", callback));
        }
        output.push_str("  },\n");
    }
    output.push_str("} as const;\n\n");

    output.push_str("export type RpcMethodName = keyof typeof rpcMethods;\n\n");

    output.push_str("export const callbackMetadata = {\n");
    for callback in ir.callbacks.values() {
        let payload = ts_type(
            ir,
            &callback.callback_payload,
            &format!("callbacks.{}.callbackPayload", callback.name),
        )?;
        output.push_str(&format!("  {}: {{\n", callback.name));
        output.push_str(&format!("    api: '{}',\n", callback.api));
        output.push_str(&format!(
            "    payload: '{}' as '{}',\n",
            type_ref_label(&callback.callback_payload),
            payload
        ));
        output.push_str(&format!(
            "    lifetime: '{}',\n",
            callback_lifetime(callback.callback_lifetime)
        ));
        output.push_str(&format!(
            "    callbackParamPosition: {},\n",
            callback.callback_param.position
        ));
        output.push_str("  },\n");
    }
    output.push_str("} as const;\n\n");

    if let Some(transaction) = &ir.transaction {
        let transaction_type = ts_type(ir, &transaction.type_ref, "transaction.type")?;
        output.push_str("export const transactionMetadata = {\n");
        output.push_str(&format!(
            "  type: '{}' as '{}',\n",
            type_ref_label(&transaction.type_ref),
            transaction_type
        ));
        output.push_str(&format!(
            "  operationVariant: '{}',\n",
            transaction.operation_variant
        ));
        output.push_str("  digest: { algorithm: 'sha256', preimage: ['chain_id', 'serialized_transaction'] },\n");
        output.push_str("  signature: { curve: 'secp256k1', format: 'graphene_compact_recoverable', canonical: true },\n");
        output.push_str("} as const;\n");
    }

    Ok(vec![GeneratedFile::new(
        PathBuf::from("typescript/index.ts"),
        output,
    )?])
}

fn ts_type(ir: &IrDocument, type_ref: &IrTypeRef, path: &str) -> Result<String, EmitError> {
    match type_ref {
        IrTypeRef::Named { name } => map_named_type(ir, name, path),
        IrTypeRef::Array { item } => Ok(format!("{}[]", ts_type(ir, item, path)?)),
        IrTypeRef::Optional { item } => Ok(format!("{} | null", ts_type(ir, item, path)?)),
    }
}

fn map_named_type(ir: &IrDocument, name: &str, path: &str) -> Result<String, EmitError> {
    let mapped = match name {
        "bool" => Some("boolean".to_owned()),
        "string" | "object_id" | "time_point_sec" | "bytes" | "signature" => {
            Some("string".to_owned())
        }
        "int8" | "uint8" | "int16" | "uint16" | "int32" | "uint32" => Some("number".to_owned()),
        "int64" | "uint64" => Some("string".to_owned()),
        "void" => Some("void".to_owned()),
        custom
            if ir.codec_types.contains_key(custom)
                || ir.operation_variants.contains_key(custom) =>
        {
            Some(custom.to_owned())
        }
        _ => None,
    };

    mapped.ok_or_else(|| EmitError::new(path, format!("cannot map IR type '{name}' to TypeScript")))
}

fn type_ref_label(type_ref: &IrTypeRef) -> String {
    match type_ref {
        IrTypeRef::Named { name } => name.clone(),
        IrTypeRef::Array { item } => format!("{}[]", type_ref_label(item)),
        IrTypeRef::Optional { item } => format!("{}?", type_ref_label(item)),
    }
}

fn named_type_name(type_ref: &IrTypeRef) -> Option<&str> {
    match type_ref {
        IrTypeRef::Named { name } => Some(name),
        _ => None,
    }
}

fn callback_lifetime(lifetime: IrCallbackLifetime) -> &'static str {
    match lifetime {
        IrCallbackLifetime::Once => "once",
        IrCallbackLifetime::Persistent => "persistent",
    }
}
