[package]
name = "open-graphene-gen"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
graphene-chain-swaplock.workspace = true
graphene-codec.workspace = true
graphene-rpc.workspace = true
graphene-signing.workspace = true
graphene-transaction.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true

[lib]
name = "open_graphene_gen"
path = "src/lib.rs"

[[bin]]
name = "open-graphene-gen"
path = "src/bin/open-graphene-gen.rs"
