use std::path::PathBuf;

use crate::emit::{EmitError, GeneratedFile};
use crate::ir::{IrCallbackLifetime, IrCodecKind, IrDocument, IrTypeRef};

pub fn emit_rust(ir: &IrDocument) -> Result<Vec<GeneratedFile>, EmitError> {
    let mut output = String::new();
    output.push_str("// @generated by open-graphene-gen. Do not edit.\n");
    output.push_str(&format!("// Chain: {}\n\n", ir.chain.name));
    output.push_str("#![allow(clippy::all)]\n\n");

    output.push_str("#[derive(Clone, Debug, PartialEq, Eq)]\n");
    output.push_str("pub struct OperationMetadata {\n");
    output.push_str("    pub id: u16,\n");
    output.push_str("    pub name: &'static str,\n");
    output.push_str("    pub type_name: &'static str,\n");
    output.push_str("}\n\n");

    output.push_str("#[derive(Clone, Debug, PartialEq, Eq)]\n");
    output.push_str("pub struct RpcMethodDescriptor {\n");
    output.push_str("    pub name: &'static str,\n");
    output.push_str("    pub api: &'static str,\n");
    output.push_str("    pub params: &'static [&'static str],\n");
    output.push_str("    pub result: Option<&'static str>,\n");
    output.push_str("    pub callback: Option<&'static str>,\n");
    output.push_str("}\n\n");

    output.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    output.push_str("pub enum CallbackLifetime {\n");
    output.push_str("    Once,\n");
    output.push_str("    Persistent,\n");
    output.push_str("}\n\n");

    output.push_str("#[derive(Clone, Debug, PartialEq, Eq)]\n");
    output.push_str("pub struct CallbackMetadata {\n");
    output.push_str("    pub name: &'static str,\n");
    output.push_str("    pub api: &'static str,\n");
    output.push_str("    pub payload: &'static str,\n");
    output.push_str("    pub lifetime: CallbackLifetime,\n");
    output.push_str("    pub callback_param_position: u16,\n");
    output.push_str("}\n\n");

    output.push_str("#[derive(Clone, Debug, PartialEq, Eq)]\n");
    output.push_str("pub struct TransactionMetadata {\n");
    output.push_str("    pub type_name: &'static str,\n");
    output.push_str("    pub operation_variant: &'static str,\n");
    output.push_str("    pub digest_algorithm: &'static str,\n");
    output.push_str("    pub digest_preimage: &'static [&'static str],\n");
    output.push_str("    pub signature_curve: &'static str,\n");
    output.push_str("    pub signature_format: &'static str,\n");
    output.push_str("    pub signature_canonical: bool,\n");
    output.push_str("}\n\n");

    for codec_type in ir.codec_types.values() {
        match codec_type.kind {
            IrCodecKind::Struct => {
                output.push_str("#[derive(Clone, Debug, PartialEq, Eq)]\n");
                output.push_str(&format!(
                    "pub struct {} {{\n",
                    rust_type_name(&codec_type.name)
                ));
                for field in &codec_type.fields {
                    let ty = rust_type(
                        ir,
                        &field.type_ref,
                        &format!("codecTypes.{}.fields.{}", codec_type.name, field.name),
                    )?;
                    output.push_str(&format!(
                        "    pub {}: {},\n",
                        rust_field_name(&field.name),
                        ty
                    ));
                }
                output.push_str("}\n\n");
            }
        }
    }

    for (name, variants) in &ir.operation_variants {
        output.push_str("#[derive(Clone, Debug, PartialEq, Eq)]\n");
        output.push_str(&format!("pub enum {} {{\n", rust_type_name(name)));
        for variant in variants {
            let variant_type = rust_type(
                ir,
                &variant.type_ref,
                &format!("operations.{name}.{}", variant.name),
            )?;
            output.push_str(&format!(
                "    {}({}),\n",
                upper_camel(&variant.name),
                variant_type
            ));
        }
        output.push_str("}\n\n");
    }

    output.push_str("pub const OPERATION_METADATA: &[OperationMetadata] = &[\n");
    for variants in ir.operation_variants.values() {
        for variant in variants {
            output.push_str(&format!(
                "    OperationMetadata {{ id: {}, name: \"{}\", type_name: \"{}\" }},\n",
                variant.id,
                variant.name,
                named_type_name(&variant.type_ref).unwrap_or("<complex>")
            ));
        }
    }
    output.push_str("];\n\n");

    output.push_str("pub const RPC_METHODS: &[RpcMethodDescriptor] = &[\n");
    for method in ir.methods.values() {
        output.push_str(&format!(
            "    RpcMethodDescriptor {{ name: \"{}\", api: \"{}\", params: &[",
            method.name, method.api
        ));
        for (index, param) in method.params.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            output.push_str(&format!("\"{}\"", type_ref_label(param)));
            let _ = rust_type(
                ir,
                param,
                &format!("methods.{}.params[{index}]", method.name),
            )?;
        }
        output.push_str("], result: ");
        if let Some(result) = &method.result {
            let _ = rust_type(ir, result, &format!("methods.{}.result", method.name))?;
            output.push_str(&format!("Some(\"{}\")", type_ref_label(result)));
        } else {
            output.push_str("None");
        }
        output.push_str(", callback: ");
        if let Some(callback) = &method.callback {
            output.push_str(&format!("Some(\"{}\")", callback));
        } else {
            output.push_str("None");
        }
        output.push_str(" },\n");
    }
    output.push_str("];\n\n");

    output.push_str("pub const CALLBACKS: &[CallbackMetadata] = &[\n");
    for callback in ir.callbacks.values() {
        let _ = rust_type(
            ir,
            &callback.callback_payload,
            &format!("callbacks.{}.callbackPayload", callback.name),
        )?;
        output.push_str(&format!(
            "    CallbackMetadata {{ name: \"{}\", api: \"{}\", payload: \"{}\", lifetime: {}, callback_param_position: {} }},\n",
            callback.name,
            callback.api,
            type_ref_label(&callback.callback_payload),
            callback_lifetime(callback.callback_lifetime),
            callback.callback_param.position
        ));
    }
    output.push_str("];\n\n");

    if let Some(transaction) = &ir.transaction {
        let _ = rust_type(ir, &transaction.type_ref, "transaction.type")?;
        output.push_str(
            "pub const TRANSACTION_METADATA: TransactionMetadata = TransactionMetadata {\n",
        );
        output.push_str(&format!(
            "    type_name: \"{}\",\n",
            type_ref_label(&transaction.type_ref)
        ));
        output.push_str(&format!(
            "    operation_variant: \"{}\",\n",
            transaction.operation_variant
        ));
        output.push_str("    digest_algorithm: \"sha256\",\n");
        output.push_str("    digest_preimage: &[\"chain_id\", \"serialized_transaction\"],\n");
        output.push_str("    signature_curve: \"secp256k1\",\n");
        output.push_str("    signature_format: \"graphene_compact_recoverable\",\n");
        output.push_str("    signature_canonical: true,\n");
        output.push_str("};\n");
    }

    Ok(vec![GeneratedFile::new(
        PathBuf::from("rust/src/lib.rs"),
        output,
    )?])
}

fn rust_type(ir: &IrDocument, type_ref: &IrTypeRef, path: &str) -> Result<String, EmitError> {
    match type_ref {
        IrTypeRef::Named { name } => map_named_type(ir, name, path),
        IrTypeRef::Array { item } => Ok(format!("Vec<{}>", rust_type(ir, item, path)?)),
        IrTypeRef::Optional { item } => Ok(format!("Option<{}>", rust_type(ir, item, path)?)),
    }
}

fn map_named_type(ir: &IrDocument, name: &str, path: &str) -> Result<String, EmitError> {
    let mapped = match name {
        "bool" => Some("bool".to_owned()),
        "string" | "object_id" | "time_point_sec" | "bytes" | "signature" | "public_key" => {
            Some("String".to_owned())
        }
        "int8" => Some("i8".to_owned()),
        "uint8" => Some("u8".to_owned()),
        "int16" => Some("i16".to_owned()),
        "uint16" => Some("u16".to_owned()),
        "int32" => Some("i32".to_owned()),
        "uint32" => Some("u32".to_owned()),
        "int64" => Some("i64".to_owned()),
        "uint64" => Some("u64".to_owned()),
        "void" => Some("()".to_owned()),
        custom
            if ir.codec_types.contains_key(custom)
                || ir.operation_variants.contains_key(custom) =>
        {
            Some(rust_type_name(custom))
        }
        _ => None,
    };

    mapped.ok_or_else(|| EmitError::new(path, format!("cannot map IR type '{name}' to Rust")))
}

fn rust_type_name(name: &str) -> String {
    upper_camel(name)
}

fn rust_field_name(name: &str) -> String {
    match name {
        "as" | "break" | "const" | "continue" | "crate" | "else" | "enum" | "extern" | "false"
        | "fn" | "for" | "if" | "impl" | "in" | "let" | "loop" | "match" | "mod" | "move"
        | "mut" | "pub" | "ref" | "return" | "self" | "Self" | "static" | "struct" | "super"
        | "trait" | "true" | "type" | "unsafe" | "use" | "where" | "while" | "async" | "await"
        | "dyn" => format!("r#{name}"),
        _ => name.to_owned(),
    }
}

fn type_ref_label(type_ref: &IrTypeRef) -> String {
    match type_ref {
        IrTypeRef::Named { name } => name.clone(),
        IrTypeRef::Array { item } => format!("{}[]", type_ref_label(item)),
        IrTypeRef::Optional { item } => format!("{}?", type_ref_label(item)),
    }
}

fn named_type_name(type_ref: &IrTypeRef) -> Option<&str> {
    match type_ref {
        IrTypeRef::Named { name } => Some(name),
        _ => None,
    }
}

fn callback_lifetime(lifetime: IrCallbackLifetime) -> &'static str {
    match lifetime {
        IrCallbackLifetime::Once => "CallbackLifetime::Once",
        IrCallbackLifetime::Persistent => "CallbackLifetime::Persistent",
    }
}

fn upper_camel(value: &str) -> String {
    let mut output = String::new();
    for part in value.split('_').filter(|part| !part.is_empty()) {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            output.extend(first.to_uppercase());
            output.push_str(chars.as_str());
        }
    }
    output
}
