// @generated by graphene-spec-gen. Do not edit.
// Chain: acta

export interface Asset {
  amount: string;
  asset_id: string;
}

export interface DynamicGlobalPropertyObject {
  head_block_number: number;
  head_block_id: string;
  time: string;
}

export interface SignedTransaction {
  ref_block_num: number;
  ref_block_prefix: number;
  expiration: string;
  operations: Operation[];
  extensions: string[];
  signatures: string[];
}

export interface SynchronousBroadcastResult {
  id: string;
  block_num: number;
  trx_num: number;
}

export interface TransferOperation {
  fee: Asset;
  from: string;
  to: string;
  amount: Asset;
  memo: string | null;
  extensions: string[];
}

export type Operation =
  { kind: 'transfer'; id: 0; value: TransferOperation };

export const operationMetadata = {
  Operation: [
    { id: 0, name: 'transfer', type: 'TransferOperation' },
  ],
} as const;

export const rpcMethods = {
  broadcast_transaction: {
    api: 'network_broadcast',
    params: ['SignedTransaction'],
    result: 'void',
  },
  broadcast_transaction_synchronous: {
    api: 'network_broadcast',
    params: ['SignedTransaction'],
    result: 'SynchronousBroadcastResult',
  },
  get_dynamic_global_properties: {
    api: 'database',
    params: [],
    result: 'DynamicGlobalPropertyObject',
  },
  set_subscribe_callback: {
    api: 'database',
    params: ['bool'],
    result: 'void',
    callback: 'set_subscribe_callback',
  },
} as const;

export type RpcMethodName = keyof typeof rpcMethods;

export const callbackMetadata = {
  set_subscribe_callback: {
    api: 'database',
    payload: 'DynamicGlobalPropertyObject' as 'DynamicGlobalPropertyObject',
    lifetime: 'persistent',
    callbackParamPosition: 0,
  },
} as const;

export const transactionMetadata = {
  type: 'SignedTransaction' as 'SignedTransaction',
  operationVariant: 'Operation',
  digest: { algorithm: 'sha256', preimage: ['chain_id', 'serialized_transaction'] },
  signature: { curve: 'secp256k1', format: 'graphene_compact_recoverable', canonical: true },
} as const;
