// @generated by graphene-spec-gen. Do not edit.
// Chain: acta

class OperationMetadata {
  final int id;
  final String name;
  final String type;

  const OperationMetadata({required this.id, required this.name, required this.type});
}

class RpcMethodDescriptor {
  final String api;
  final List<String> params;
  final String? result;
  final String? callback;

  const RpcMethodDescriptor({required this.api, required this.params, this.result, this.callback});
}

class CallbackMetadata {
  final String api;
  final String payload;
  final String lifetime;
  final int callbackParamPosition;

  const CallbackMetadata({required this.api, required this.payload, required this.lifetime, required this.callbackParamPosition});
}

class TransactionDigestMetadata {
  final String algorithm;
  final List<String> preimage;

  const TransactionDigestMetadata({required this.algorithm, required this.preimage});
}

class TransactionSignatureMetadata {
  final String curve;
  final String format;
  final bool canonical;

  const TransactionSignatureMetadata({required this.curve, required this.format, required this.canonical});
}

class TransactionMetadata {
  final String type;
  final String operationVariant;
  final TransactionDigestMetadata digest;
  final TransactionSignatureMetadata signature;

  const TransactionMetadata({required this.type, required this.operationVariant, required this.digest, required this.signature});
}

abstract class Operation {
  int get id;
  String get kind;
  Object get value;

  const Operation();
}

class Asset {
  final String amount;
  final String asset_id;

  const Asset({
    required this.amount,
    required this.asset_id,
  });
}

class DynamicGlobalPropertyObject {
  final int head_block_number;
  final String head_block_id;
  final String time;

  const DynamicGlobalPropertyObject({
    required this.head_block_number,
    required this.head_block_id,
    required this.time,
  });
}

class SignedTransaction {
  final int ref_block_num;
  final int ref_block_prefix;
  final String expiration;
  final List<Operation> operations;
  final List<String> extensions;
  final List<String> signatures;

  const SignedTransaction({
    required this.ref_block_num,
    required this.ref_block_prefix,
    required this.expiration,
    required this.operations,
    required this.extensions,
    required this.signatures,
  });
}

class SynchronousBroadcastResult {
  final String id;
  final int block_num;
  final int trx_num;

  const SynchronousBroadcastResult({
    required this.id,
    required this.block_num,
    required this.trx_num,
  });
}

class TransferOperation {
  final Asset fee;
  final String from;
  final String to;
  final Asset amount;
  final String? memo;
  final List<String> extensions;

  const TransferOperation({
    required this.fee,
    required this.from,
    required this.to,
    required this.amount,
    required this.memo,
    required this.extensions,
  });
}

class TransferOperationOperation extends Operation {
  final TransferOperation typedValue;

  const TransferOperationOperation(this.typedValue);

  @override
  int get id => 0;

  @override
  String get kind => 'transfer';

  @override
  Object get value => typedValue;
}

const Map<String, List<OperationMetadata>> operationMetadata = {
  'Operation': [
    OperationMetadata(id: 0, name: 'transfer', type: 'TransferOperation'),
  ],
};

const Map<String, RpcMethodDescriptor> rpcMethods = {
  'broadcast_transaction': RpcMethodDescriptor(
    api: 'network_broadcast',
    params: ['SignedTransaction'],
    result: 'void',
  ),
  'broadcast_transaction_synchronous': RpcMethodDescriptor(
    api: 'network_broadcast',
    params: ['SignedTransaction'],
    result: 'SynchronousBroadcastResult',
  ),
  'get_dynamic_global_properties': RpcMethodDescriptor(
    api: 'database',
    params: [],
    result: 'DynamicGlobalPropertyObject',
  ),
  'set_subscribe_callback': RpcMethodDescriptor(
    api: 'database',
    params: ['bool'],
    result: 'void',
    callback: 'set_subscribe_callback',
  ),
};

const Map<String, CallbackMetadata> callbackMetadata = {
  'set_subscribe_callback': CallbackMetadata(
    api: 'database',
    payload: 'DynamicGlobalPropertyObject',
    lifetime: 'persistent',
    callbackParamPosition: 0,
  ),
};

const TransactionMetadata transactionMetadata = TransactionMetadata(
  type: 'SignedTransaction',
  operationVariant: 'Operation',
  digest: TransactionDigestMetadata(algorithm: 'sha256', preimage: ['chain_id', 'serialized_transaction']),
  signature: TransactionSignatureMetadata(curve: 'secp256k1', format: 'graphene_compact_recoverable', canonical: true),
);
