// @generated by open-graphene-gen. Do not edit.
// Chain: acta

#![allow(clippy::all)]

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct OperationMetadata {
    pub id: u16,
    pub name: &'static str,
    pub type_name: &'static str,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RpcMethodDescriptor {
    pub name: &'static str,
    pub api: &'static str,
    pub params: &'static [&'static str],
    pub result: Option<&'static str>,
    pub callback: Option<&'static str>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CallbackLifetime {
    Once,
    Persistent,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CallbackMetadata {
    pub name: &'static str,
    pub api: &'static str,
    pub payload: &'static str,
    pub lifetime: CallbackLifetime,
    pub callback_param_position: u16,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TransactionMetadata {
    pub type_name: &'static str,
    pub operation_variant: &'static str,
    pub digest_algorithm: &'static str,
    pub digest_preimage: &'static [&'static str],
    pub signature_curve: &'static str,
    pub signature_format: &'static str,
    pub signature_canonical: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Asset {
    pub amount: i64,
    pub asset_id: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DynamicGlobalPropertyObject {
    pub head_block_number: u32,
    pub head_block_id: String,
    pub time: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SignedTransaction {
    pub ref_block_num: u16,
    pub ref_block_prefix: u32,
    pub expiration: String,
    pub operations: Vec<Operation>,
    pub extensions: Vec<String>,
    pub signatures: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SynchronousBroadcastResult {
    pub id: String,
    pub block_num: u32,
    pub trx_num: u32,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TransferOperation {
    pub fee: Asset,
    pub from: String,
    pub to: String,
    pub amount: Asset,
    pub memo: Option<String>,
    pub extensions: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Operation {
    Transfer(TransferOperation),
}

pub const OPERATION_METADATA: &[OperationMetadata] = &[
    OperationMetadata { id: 0, name: "transfer", type_name: "TransferOperation" },
];

pub const RPC_METHODS: &[RpcMethodDescriptor] = &[
    RpcMethodDescriptor { name: "broadcast_transaction", api: "network_broadcast", params: &["SignedTransaction"], result: Some("void"), callback: None },
    RpcMethodDescriptor { name: "broadcast_transaction_synchronous", api: "network_broadcast", params: &["SignedTransaction"], result: Some("SynchronousBroadcastResult"), callback: None },
    RpcMethodDescriptor { name: "get_dynamic_global_properties", api: "database", params: &[], result: Some("DynamicGlobalPropertyObject"), callback: None },
    RpcMethodDescriptor { name: "set_subscribe_callback", api: "database", params: &["bool"], result: Some("void"), callback: Some("set_subscribe_callback") },
];

pub const CALLBACKS: &[CallbackMetadata] = &[
    CallbackMetadata { name: "set_subscribe_callback", api: "database", payload: "DynamicGlobalPropertyObject", lifetime: CallbackLifetime::Persistent, callback_param_position: 0 },
];

pub const TRANSACTION_METADATA: TransactionMetadata = TransactionMetadata {
    type_name: "SignedTransaction",
    operation_variant: "Operation",
    digest_algorithm: "sha256",
    digest_preimage: &["chain_id", "serialized_transaction"],
    signature_curve: "secp256k1",
    signature_format: "graphene_compact_recoverable",
    signature_canonical: true,
};
